import ImageTracer from 'imagetracerjs';
import './flash-editor.css';
import './flash-levels.css';

function initFlashEditor() {
  if (new URLSearchParams(location.search).get('studio') !== 'flash') return;
  const workspace = document.querySelector('.workspace');
  if (!workspace) return;
  workspace.innerHTML = `<section class="flash-editor"><header><div><small>PRÉPARATION DU TRAIT</small><h2>Vectoriser puis calibrer le dessin</h2></div><label class="flash-import">Importer un dessin<input id="flash-file" type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml"/></label></header><div class="flash-stage"><div id="flash-preview" aria-label="Aperçu vectorisé du motif"><span>Importez un motif pour afficher ses contours.</span></div><p id="flash-status">Le dessin reste sur cet appareil.</p></div></section><aside class="flash-controls"><p>01 / VECTORISATION FIDÈLE</p><button class="flash-auto" id="flash-auto" disabled>Optimiser automatiquement</button><label>Point noir <output id="flash-black-out">25</output></label><input id="flash-black" type="range" min="0" max="180" value="25"/><label>Gris / gamma <output id="flash-gamma-out">1,00</output></label><input id="flash-gamma" type="range" min="0.45" max="1.80" step="0.05" value="1"/><label>Point blanc <output id="flash-white-out">245</output></label><input id="flash-white" type="range" min="80" max="255" value="245"/><label>Seuil de tolérance <output id="flash-threshold-out">145</output></label><input id="flash-threshold" type="range" min="25" max="235" value="145"/><small>Les niveaux séparent les noirs, gris et blancs avant le traçage. L’optimisation calcule une base selon votre image.</small><hr/><p>02 / AIGUILLES</p><div id="needle-presets"><button class="active" data-width="0.25">1RL · 0,25 mm</button><button data-width="0.30">3RL · 0,30 mm</button><button data-width="0.35">5RL · 0,35 mm</button><button data-width="0.40">7RL · 0,40 mm</button><button data-width="0.45">9RL · 0,45 mm</button></div><small>Diamètres indicatifs : vérifiez toujours la fiche du fabricant et votre configuration.</small><hr/><p>03 / TRAIT SÉLECTIONNÉ</p><label>Épaisseur <output id="flash-stroke-out">0,25 mm</output></label><input id="flash-stroke" type="range" min="0.15" max="1.20" step="0.05" value="0.25"/><small id="flash-line-status">Cliquez un contour dans l’aperçu pour régler ce trait individuellement.</small><button class="primary flash-export" id="flash-export" disabled>Exporter le stencil SVG</button></aside>`;
  const $ = selector => document.querySelector(selector), preview = $('#flash-preview');
  let source, selectedPath, svgText = '';
  const updateOutput = () => { ['black','white','threshold'].forEach(id => $(`#flash-${id}-out`).textContent = $(`#flash-${id}`).value); $('#flash-gamma-out').textContent = Number($('#flash-gamma').value).toFixed(2).replace('.', ','); $('#flash-stroke-out').textContent = `${Number($('#flash-stroke').value).toFixed(2).replace('.', ',')} mm`; };
  const selectPath = path => { selectedPath?.classList.remove('selected'); selectedPath = path; selectedPath?.classList.add('selected'); if (path) { const width = Number(path.dataset.width || $('#flash-stroke').value); $('#flash-stroke').value = width; updateOutput(); $('#flash-line-status').textContent = 'Contour sélectionné : son épaisseur est indépendante des autres.'; } };
  const originalImageData = () => { const max = 900, ratio = Math.min(1, max / Math.max(source.naturalWidth || source.width, source.naturalHeight || source.height)), canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round((source.naturalWidth || source.width) * ratio)); canvas.height = Math.max(1, Math.round((source.naturalHeight || source.height) * ratio)); const context = canvas.getContext('2d', { willReadFrequently: true }); context.drawImage(source, 0, 0, canvas.width, canvas.height); return context.getImageData(0, 0, canvas.width, canvas.height); };
  const autoLevels = () => { if (!source) return; const pixels = originalImageData().data, histogram = new Array(256).fill(0); for (let i = 0; i < pixels.length; i += 4) histogram[Math.round(.2126 * pixels[i] + .7152 * pixels[i + 1] + .0722 * pixels[i + 2])]++; const total = pixels.length / 4, percentile = value => { let count = 0; for (let i = 0; i < 256; i++) { count += histogram[i]; if (count >= total * value) return i; } return 255; }; let sum = 0, sumBackground = 0, weightBackground = 0, best = 0, maximum = 0; histogram.forEach((count, index) => sum += index * count); for (let index = 0; index < 256; index++) { weightBackground += histogram[index]; if (!weightBackground) continue; const weightForeground = total - weightBackground; if (!weightForeground) break; sumBackground += index * histogram[index]; const variance = weightBackground * weightForeground * (sumBackground / weightBackground - (sum - sumBackground) / weightForeground) ** 2; if (variance > maximum) { maximum = variance; best = index; } } const highContrast = best < 20 || best > 235, black = highContrast ? 0 : Math.max(0, percentile(.01) - 5), white = highContrast ? 255 : Math.min(255, percentile(.99) + 5), normalizedThreshold = highContrast ? 128 : Math.max(25, Math.min(235, Math.round((best - black) * 255 / Math.max(1, white - black)))); $('#flash-black').value = black; $('#flash-white').value = Math.max(black + 20, white); $('#flash-threshold').value = normalizedThreshold; $('#flash-gamma').value = '1'; updateOutput(); vectorize(); $('#flash-status').textContent = 'Niveaux optimisés automatiquement à partir des noirs, gris et blancs du dessin.'; };
  const vectorize = () => {
    if (!source) return;
    const imageData = originalImageData(), threshold = Number($('#flash-threshold').value), black = Number($('#flash-black').value), white = Math.max(black + 1, Number($('#flash-white').value)), gamma = Number($('#flash-gamma').value), pixels = imageData.data;
    for (let i = 0; i < pixels.length; i += 4) { const light = .2126 * pixels[i] + .7152 * pixels[i + 1] + .0722 * pixels[i + 2], adjusted = 255 * Math.pow(Math.max(0, Math.min(1, (light - black) / (white - black))), 1 / gamma), value = adjusted < threshold ? 0 : 255; pixels[i] = pixels[i + 1] = pixels[i + 2] = value; }
    svgText = ImageTracer.imagedataToSVG(imageData, { numberofcolors: 2, colorquantcycles: 1, pathomit: 8, ltres: .55, qtres: .55, rightangleenhance: true, blurradius: 0 });
    preview.innerHTML = svgText; const svg = preview.querySelector('svg'); svg.setAttribute('preserveAspectRatio', 'xMidYMid meet'); svg.querySelectorAll('path').forEach(path => { path.setAttribute('fill', 'none'); path.setAttribute('stroke', '#101114'); path.setAttribute('stroke-linecap', 'round'); path.setAttribute('stroke-linejoin', 'round'); path.dataset.width = $('#flash-stroke').value; path.setAttribute('stroke-width', path.dataset.width); path.onclick = () => selectPath(path); });
    $('#flash-status').textContent = `${svg.querySelectorAll('path').length} contours vectorisés · cliquez un trait pour le calibrer.`; $('#flash-export').disabled = false;
  };
  const loadImage = file => { if (!file?.type.startsWith('image/')) return; const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { source = image; $('#flash-auto').disabled = false; autoLevels(); }; image.src = reader.result; }; reader.readAsDataURL(file); };
  $('#flash-file').onchange = event => loadImage(event.target.files[0]);
  ['black','gamma','white','threshold'].forEach(id => $(`#flash-${id}`).oninput = () => { updateOutput(); vectorize(); });
  $('#flash-auto').onclick = autoLevels;
  $('#flash-stroke').oninput = () => { updateOutput(); if (selectedPath) { selectedPath.dataset.width = $('#flash-stroke').value; selectedPath.setAttribute('stroke-width', selectedPath.dataset.width); } };
  $('#needle-presets').onclick = event => { const button = event.target.closest('button'); if (!button) return; document.querySelectorAll('#needle-presets button').forEach(item => item.classList.toggle('active', item === button)); $('#flash-stroke').value = button.dataset.width; updateOutput(); if (selectedPath) { selectedPath.dataset.width = button.dataset.width; selectedPath.setAttribute('stroke-width', button.dataset.width); } };
  $('#flash-export').onclick = () => { const svg = preview.querySelector('svg'); if (!svg) return; const blob = new Blob([new XMLSerializer().serializeToString(svg)], { type: 'image/svg+xml' }), link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'kanaforge-stencil.svg'; link.click(); URL.revokeObjectURL(link.href); };
}

if (document.readyState === 'loading') addEventListener('DOMContentLoaded', initFlashEditor, { once: true }); else queueMicrotask(initFlashEditor);
