import * as THREE from 'https://cdn.jsdelivr.net/npm/three@0.169.0/build/three.module.js';
import { OrbitControls } from 'https://cdn.jsdelivr.net/npm/three@0.169.0/examples/jsm/controls/OrbitControls.js';
import './style.css';
import './exports.css';
import './preview.css';
import './rebrand.css';
import './fidelity.css';

const $=s=>document.querySelector(s),sourceCanvas=$('#source-canvas'),sourceCtx=sourceCanvas.getContext('2d',{willReadFrequently:true}),afterCanvas=$('#after-canvas'),afterCtx=afterCanvas.getContext('2d');
let imageReady=false,geometry,mesh,material,texture,bgTexture,fileName='',isPlaying=true,last=performance.now(),recording=false;
const viewport=$('#viewport'),stage=$('#stage'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,1000),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x101820,1);stage.append(renderer.domElement);camera.position.set(83,72,112);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=45;controls.maxDistance=250;controls.target.set(0,0,6);
const ambient=new THREE.HemisphereLight(0xd6f3ff,0x081311,1.1),key=new THREE.DirectionalLight(0xffefd0,3.4),rim=new THREE.DirectionalLight(0x68d7c3,1.4);scene.add(ambient,key,rim);rim.position.set(-55,25,-35);
function resize(){const r=stage.getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height)}new ResizeObserver(resize).observe(stage);resize();
const units={height:' mm',threshold:'',scale:' %',light:'°',shadow:' %',saturation:' %',brightness:' %',orientation:'°',speed:'×'};
const profiles={instagram:{w:1080,h:1920,label:'Instagram Reel — 1080 × 1920'},square:{w:1080,h:1080,label:'Publication carrée — 1080 × 1080'},landscape:{w:1920,h:1080,label:'Paysage — 1920 × 1080'},'4k':{w:2160,h:3840,label:'Haute définition — 2160 × 3840'}};
function exportOptions(){const p=profiles[$('#profile').value],seconds=+$('#duration').value,quality=$('#quality').value,bitrate={standard:4500000,high:9000000,maximum:16000000}[quality];return{...p,seconds,bitrate}}
function refreshExportUi(){const o=exportOptions();$('#duration-label').textContent='00:'+String(o.seconds).padStart(2,'0');$('.timeline i').style.animationDuration=o.seconds+'s';$('#export-note').textContent=`${o.label}, 30 i/s, qualité ${$('#quality').selectedOptions[0].text.toLowerCase()}.`;$('#record').textContent=$('#profile').value==='instagram'?'● Créer la vidéo Instagram':'● Créer la vidéo'}
for(const id of Object.keys(units))$('#'+id).addEventListener('input',()=>{const val=+$('#'+id).value;$('#'+id+'-out').textContent=id==='speed'?(val/10).toFixed(1)+'×':val+units[id];if(id==='light'||id==='shadow')setLighting();else if(id==='scale'||id==='orientation')setTransform();else if(id==='saturation'||id==='brightness')setBackgroundStyle();else if(imageReady)buildModel()});
function setLighting(){const a=+$('#light').value*Math.PI/180,intensity=1.1+(100-+$('#shadow').value)/35;key.position.set(Math.cos(a)*95,Math.sin(a)*95,60);key.intensity=intensity;ambient.intensity=.5+(100-+$('#shadow').value)/120}
function setTransform(){if(!mesh)return;const s=+$('#scale').value/100;mesh.scale.setScalar(s);mesh.rotation.z=+$('#orientation').value*Math.PI/180}
function setBackgroundStyle(){const saturate=$('#saturation').value,bright=$('#brightness').value;viewport.style.filter=`saturate(${saturate}%) brightness(${bright}%)`;if(!bgTexture)scene.background=new THREE.Color($('#bg-color').value)}
function updateAfter(){if(!imageReady)return;afterCanvas.width=sourceCanvas.width;afterCanvas.height=sourceCanvas.height;afterCtx.drawImage(renderer.domElement,0,0,afterCanvas.width,afterCanvas.height)}
function frame(now){requestAnimationFrame(frame);const delta=Math.min(.05,(now-last)/1000);last=now;if(mesh&&isPlaying)mesh.rotation.y+=delta*(+$('#speed').value/10);controls.update();renderer.render(scene,camera);if(Math.round(now)%10===0)updateAfter()}requestAnimationFrame(frame);
function setEffect(){if(!material)return;const effect=$('.effects .chosen').dataset.effect;const cfg={metal:{color:0xb7c6c2,roughness:.22,metalness:.95,emissive:0x000000},hologram:{color:0x39e7db,roughness:.1,metalness:.5,emissive:0x087c78},stone:{color:0x8d8b83,roughness:.94,metalness:0,emissive:0x000000},cracked:{color:0x382e29,roughness:.72,metalness:.08,emissive:0x000000},barbed:{color:0x5c6870,roughness:.42,metalness:.86,emissive:0x000000},liquid:{color:0x9ba9bd,roughness:.04,metalness:1,emissive:0x111827}}[effect];material.color.setHex(cfg.color);material.roughness=cfg.roughness;material.metalness=cfg.metalness;material.emissive.setHex(cfg.emissive);material.emissiveIntensity=effect==='hologram'?1.3:0;material.wireframe=effect==='barbed';material.transparent=effect==='hologram';material.opacity=effect==='hologram'?.78:1;$('#effect-label').textContent=$('.effects .chosen').textContent}
function buildModel(){if(!imageReady)return;const height=+$('#height').value,threshold=+$('#threshold').value,cols=110,ratio=sourceCanvas.width/sourceCanvas.height,rows=Math.max(18,Math.round(cols/ratio)),sample=document.createElement('canvas');sample.width=cols;sample.height=rows;const sc=sample.getContext('2d',{willReadFrequently:true});sc.drawImage(sourceCanvas,0,0,cols,rows);const pix=sc.getImageData(0,0,cols,rows).data,pos=[],idx=[],sx=118/cols,sy=118/ratio/rows;let vi=0;for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const k=(y*cols+x)*4,l=.2126*pix[k]+.7152*pix[k+1]+.0722*pix[k+2],a=Math.max(0,Math.min(1,(threshold-l)/threshold));if(a<.1)continue;const x0=(x-cols/2)*sx,x1=x0+sx,y0=(rows/2-y)*sy,y1=y0-sy,z=height*(.4+.6*a);pos.push(x0,y0,0,x1,y0,0,x1,y1,0,x0,y1,0,x0,y0,z,x1,y0,z,x1,y1,z,x0,y1,z);for(const f of[[0,1,2,3],[4,7,6,5],[0,4,5,1],[1,5,6,2],[2,6,7,3],[3,7,4,0]])idx.push(vi+f[0],vi+f[1],vi+f[2],vi+f[0],vi+f[2],vi+f[3]);vi+=8}geometry?.dispose();geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geometry.setIndex(idx);geometry.computeVertexNormals();if(mesh)scene.remove(mesh);material?.dispose();material=new THREE.MeshStandardMaterial({map:texture,color:0xb7c6c2,roughness:.22,metalness:.95});mesh=new THREE.Mesh(geometry,material);scene.add(mesh);setEffect();setTransform()}
function loadDrawing(file){fileName=file.name;$('#file-name').textContent=file.name;const img=new Image();img.onload=()=>{const scale=Math.min(1,1000/Math.max(img.width,img.height));sourceCanvas.width=Math.round(img.width*scale);sourceCanvas.height=Math.round(img.height*scale);sourceCtx.fillStyle='#fff';sourceCtx.fillRect(0,0,sourceCanvas.width,sourceCanvas.height);sourceCtx.drawImage(img,0,0,sourceCanvas.width,sourceCanvas.height);URL.revokeObjectURL(img.src);imageReady=true;buildModel();$('#empty').classList.add('hidden');$('#record').disabled=false;$('#stl').disabled=false;$('#status').className='ready';$('#status').innerHTML='<i></i> Rendu 3D en direct'};img.src=URL.createObjectURL(file)}
$('#file-input').addEventListener('change',e=>e.target.files[0]&&loadDrawing(e.target.files[0]));const dz=$('#dropzone');['dragenter','dragover'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.add('drag')}));['dragleave','drop'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>e.dataTransfer.files[0]&&loadDrawing(e.dataTransfer.files[0]));
$('#effects').addEventListener('click',e=>{if(!e.target.dataset.effect)return;$('.effects .chosen').classList.remove('chosen');e.target.classList.add('chosen');setEffect()});
$('#texture-input').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const url=URL.createObjectURL(f);new THREE.TextureLoader().load(url,t=>{texture?.dispose();texture=t;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(3,3);if(material){material.map=texture;material.needsUpdate=true}URL.revokeObjectURL(url)})});
$('#bg-color').addEventListener('input',()=>{bgTexture=null;setBackgroundStyle()});$('#bg-image').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const u=URL.createObjectURL(f);new THREE.TextureLoader().load(u,t=>{bgTexture=t;scene.background=t;URL.revokeObjectURL(u)})});$('#bg-color').value='#000000';setBackgroundStyle();setLighting();
$('#pause').addEventListener('click',()=>{isPlaying=!isPlaying;$('#pause').textContent=isPlaying?'❚❚  Pause':'▶  Lecture'});document.querySelectorAll('.format button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.format-active').classList.remove('format-active');b.classList.add('format-active');viewport.classList.toggle('square',b.dataset.format==='square')}));
['profile','quality','duration'].forEach(id=>$('#'+id).addEventListener('change',refreshExportUi));refreshExportUi();
$('#record').addEventListener('click',()=>{if(recording)return;recording=true;const o=exportOptions(),button=$('#record'),chunks=[],oldSize=renderer.getSize(new THREE.Vector2()),oldRatio=renderer.getPixelRatio();renderer.setPixelRatio(1);renderer.setSize(o.w,o.h,false);const preferred='video/mp4;codecs=avc1.42E01E',mime=MediaRecorder.isTypeSupported(preferred)?preferred:'video/webm;codecs=vp9',extension=mime.startsWith('video/mp4')?'mp4':'webm',stream=renderer.domElement.captureStream(30),rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:o.bitrate});rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{renderer.setPixelRatio(oldRatio);renderer.setSize(oldSize.x,oldSize.y,false);const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:mime}));a.download=(fileName.replace(/\.[^/.]+$/,'')||'reel')+'-3d.'+extension;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);recording=false;refreshExportUi();$('#status').innerHTML='<i></i> Vidéo prête au téléchargement'};rec.start();button.textContent='● Enregistrement…';$('#status').innerHTML='<i></i> Création de la vidéo '+o.seconds+' s';setTimeout(()=>rec.stop(),o.seconds*1000)});
$('#stl').addEventListener('click',()=>{if(!geometry)return;const p=geometry.getAttribute('position'),ind=geometry.getIndex(),v=i=>new THREE.Vector3(p.getX(i),p.getY(i),p.getZ(i));let s='solid calligraphy\n';for(let i=0;i<ind.count;i+=3){const a=v(ind.getX(i)),b=v(ind.getX(i+1)),c=v(ind.getX(i+2)),n=new THREE.Vector3().crossVectors(b.clone().sub(a),c.clone().sub(a)).normalize();s+=`facet normal ${n.x} ${n.y} ${n.z}\n outer loop\n  vertex ${a.x} ${a.y} ${a.z}\n  vertex ${b.x} ${b.y} ${b.z}\n  vertex ${c.x} ${c.y} ${c.z}\n endloop\nendfacet\n`}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s+'endsolid calligraphy\n'],{type:'model/stl'}));a.download='dessin-3d.stl';a.click()});
