import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import { Reflector } from 'three/examples/jsm/objects/Reflector.js';
import { SVGLoader } from 'three/examples/jsm/loaders/SVGLoader.js';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import ImageTracer from 'imagetracerjs';
import './style.css';
import './exports.css';
import './preview.css';
import './rebrand.css';
import './fidelity.css';
import './textures.css';
import './import-preview.css';
import './modelize.css';
import './volume.css';
import './vectorize.css';

const $=s=>document.querySelector(s),sourceCanvas=$('#source-canvas'),sourceCtx=sourceCanvas.getContext('2d',{willReadFrequently:true}),afterCanvas=$('#after-canvas'),afterCtx=afterCanvas.getContext('2d');
let imageReady=false,modelReady=false,vectorized=true,geometry,mesh,material,texture,bgTexture,fileName='',isPlaying=false,last=performance.now(),recording=false,selectedFinish='chrome',trailEnabled=false,trailMeshes=[],trailHistory=[],trailLast=0;
const viewport=$('#viewport'),stage=$('#stage'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,1000),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});
const pmrem=new THREE.PMREMGenerator(renderer),studioEnvironment=pmrem.fromScene(new RoomEnvironment(),.04).texture,chromeCanvas=document.createElement('canvas');chromeCanvas.width=1024;chromeCanvas.height=512;const chromeCtx=chromeCanvas.getContext('2d'),chromeGradient=chromeCtx.createLinearGradient(0,0,1024,0);chromeGradient.addColorStop(0,'#010103');chromeGradient.addColorStop(.12,'#080b0f');chromeGradient.addColorStop(.24,'#edf8ff');chromeGradient.addColorStop(.31,'#18232c');chromeGradient.addColorStop(.49,'#ffffff');chromeGradient.addColorStop(.59,'#101820');chromeGradient.addColorStop(.72,'#d6f4ff');chromeGradient.addColorStop(.82,'#06090d');chromeGradient.addColorStop(1,'#020204');chromeCtx.fillStyle=chromeGradient;chromeCtx.fillRect(0,0,1024,512);const chromeTexture=new THREE.CanvasTexture(chromeCanvas);chromeTexture.mapping=THREE.EquirectangularReflectionMapping;chromeTexture.colorSpace=THREE.SRGBColorSpace;const chromeEnvironment=pmrem.fromEquirectangular(chromeTexture).texture;scene.environment=chromeEnvironment;
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x101820,1);stage.append(renderer.domElement);camera.position.set(83,72,112);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=45;controls.maxDistance=250;controls.target.set(0,0,6);
const ambient=new THREE.HemisphereLight(0xd6f3ff,0x081311,1.1),key=new THREE.DirectionalLight(0xffefd0,3.4),rim=new THREE.DirectionalLight(0x68d7c3,1.4),neonLight=new THREE.PointLight(0x48dfff,0,180,2),mirrorFloor=new Reflector(new THREE.PlaneGeometry(600,600),{textureWidth:512,textureHeight:512,color:0x091017,clipBias:.003});scene.add(ambient,key,rim,neonLight);rim.position.set(-55,25,-35);mirrorFloor.rotateX(-Math.PI/2);mirrorFloor.position.y=-64;mirrorFloor.visible=false;scene.add(mirrorFloor);const accentLights=[],accentPalette=[0xff5f9f,0x6ae9ff,0xb68cff,0xffc66a];let accentIndex=0;
function resize(){const r=stage.getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height)}new ResizeObserver(resize).observe(stage);resize();
$('.material-card').insertAdjacentHTML('beforeend','<div class="color-row"><label>Couleur métal<input id="material-color" type="color" value="#b7c6c2"/></label><label>Lueur<input id="emissive-color" type="color" value="#071116"/></label></div><label>Réflexion <output id="reflect-out">85 %</output></label><input id="reflect" type="range" min="0" max="100" value="85"/>');$('.light-card').insertAdjacentHTML('beforeend','<div class="color-row"><label>Clé<input id="light-color" type="color" value="#ffefd0"/></label><label>Contour<input id="rim-color" type="color" value="#68d7c3"/></label></div><label>Puissance <output id="light-power-out">100 %</output></label><input id="light-power" type="range" min="20" max="220" value="100"/><label>Exposition <output id="exposure-out">100 %</output></label><input id="exposure" type="range" min="40" max="180" value="100"/><button id="add-accent-light" class="secondary" type="button">＋ Ajouter une lumière d’accent</button>');$('.decor-card').insertAdjacentHTML('beforeend','<button id="mirror-floor-toggle" class="secondary" type="button">Activer le sol miroir</button>');
$('#effects').insertAdjacentHTML('beforeend','<button data-effect="metal" data-finish="translucent">Translucide</button><button data-effect="metal" data-finish="chrome">Métal chromé</button><button data-effect="neon">Néon lumineux</button>');
$('#height').max=100;$('#volume-styles').insertAdjacentHTML('afterend','<label>Relief de surface</label><div class="volume-styles" id="relief-profiles"><button class="chosen" data-relief="geometric">Géométrique</button><button data-relief="smooth">Lisse</button><button data-relief="sharp">Saillant</button><button data-relief="spiky">Épineux</button></div>');$('.motion-card').insertAdjacentHTML('beforeend','<label>Étirement en mouvement</label><button id="motion-echo" class="secondary" type="button">Activer l’écho de mouvement</button><label>Images fantômes <output id="echo-frames-out">8</output></label><input id="echo-frames" type="range" min="2" max="16" value="8"/>');$('#demodelize').insertAdjacentHTML('afterend','<button id="randomize" class="secondary" type="button">✦ Paramètres aléatoires</button>');
const units={height:' mm',threshold:'',detail:' %',fill:' %',scale:' %',light:'°',shadow:' %','light-power':' %',exposure:' %',reflect:' %',saturation:' %',brightness:' %',orientation:'°',speed:'×',slowdown:' %','position-x':'','position-y':''};
const libraryTextures={wood:new URL('../assets/textures/fine-grained-wood-1k.jpg',import.meta.url).href,concrete:new URL('../assets/textures/rough-concrete-1k.jpg',import.meta.url).href,fabric:new URL('../assets/textures/fabric-pattern-05-1k.jpg',import.meta.url).href};
const profiles={instagram:{w:1080,h:1920,label:'Instagram Reel — 1080 × 1920'},square:{w:1080,h:1080,label:'Publication carrée — 1080 × 1080'},landscape:{w:1920,h:1080,label:'Paysage — 1920 × 1080'},'4k':{w:2160,h:3840,label:'Haute définition — 2160 × 3840'}};
function exportOptions(){const p=profiles[$('#profile').value],seconds=+$('#duration').value,quality=$('#quality').value,bitrate={standard:4500000,high:9000000,maximum:16000000}[quality];return{...p,seconds,bitrate}}
function refreshExportUi(){const o=exportOptions();$('#duration-label').textContent='00:'+String(o.seconds).padStart(2,'0');$('.timeline i').style.animationDuration=o.seconds+'s';$('#export-note').textContent=`${o.label}, 30 i/s, qualité ${$('#quality').selectedOptions[0].text.toLowerCase()}.`;$('#record').textContent=$('#profile').value==='instagram'?'● Créer la vidéo Instagram':'● Créer la vidéo'}
for(const id of Object.keys(units))$('#'+id).addEventListener('input',()=>{const val=+$('#'+id).value;$('#'+id+'-out').textContent=id==='speed'?(val/10).toFixed(1)+'×':val+units[id];if(id==='light'||id==='shadow')setLighting();else if(id==='scale'||id==='orientation'||id==='position-x'||id==='position-y')setTransform();else if(id==='speed'||id==='slowdown'){}else if(id==='saturation'||id==='brightness')setBackgroundStyle();else if(modelReady)(vectorized?buildVectorModel():buildModel())});
function setLighting(){const a=+$('#light').value*Math.PI/180,intensity=(1.1+(100-+$('#shadow').value)/35)*(+$('#light-power').value/100);key.position.set(Math.cos(a)*95,Math.sin(a)*95,60);key.intensity=intensity;key.color.set($('#light-color').value);rim.color.set($('#rim-color').value);ambient.intensity=.5+(100-+$('#shadow').value)/120;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=+$('#exposure').value/100}
function addAccentLight(){const angle=(accentIndex*93+125)*Math.PI/180,light=new THREE.DirectionalLight(accentPalette[accentIndex%accentPalette.length],2.3);light.position.set(Math.cos(angle)*105,32+accentIndex%3*22,Math.sin(angle)*105);light.target.position.set(0,0,8);scene.add(light,light.target);accentLights.push(light);accentIndex++;$('#add-accent-light').textContent='＋ Lumières d’accent : '+accentLights.length}
function randomizeScene(){const set=(id,min,max)=>{const input=$('#'+id);input.value=Math.round(min+Math.random()*(max-min));input.dispatchEvent(new Event('input',{bubbles:true}))};set('height',6,38);set('threshold',70,200);set('detail',20,85);set('scale',75,120);set('light',0,360);set('shadow',20,80);set('light-power',60,180);set('exposure',70,135);set('orientation',0,360);set('speed',4,20);set('slowdown',30,92);set('position-x',-20,20);set('position-y',-14,14);$('#bg-color').value=['#03070f','#08000f','#07140f','#120607'][Math.floor(Math.random()*4)];setBackgroundStyle();const options=[...document.querySelectorAll('#effects button[data-effect]')],choice=options[Math.floor(Math.random()*options.length)];choice.click();$('#status').className='ready';$('#status').innerHTML='<i></i> Variante aléatoire générée'}
['light-power','exposure','light-color','rim-color'].forEach(id=>$('#'+id).addEventListener('input',setLighting));['material-color','emissive-color'].forEach(id=>$('#'+id).addEventListener('input',()=>{if(!material)return;material.color.set($('#material-color').value);material.emissive.set($('#emissive-color').value);material.needsUpdate=true}));$('#reflect').addEventListener('input',()=>{if(!material)return;material.metalness=+$('#reflect').value/100;material.roughness=1-(+$('#reflect').value/100)*.8;material.needsUpdate=true});
function setTransform(){if(!mesh)return;const s=+$('#scale').value/100;mesh.scale.setScalar(s);mesh.rotation.z=+$('#orientation').value*Math.PI/180;mesh.position.set(+$('#position-x').value,+$('#position-y').value,0)}
function clearTrail(){trailMeshes.forEach(item=>{scene.remove(item);item.material.dispose()});trailMeshes=[];trailHistory=[]}
function updateTrail(now){if(!trailEnabled||!mesh||!material){trailMeshes.forEach(item=>item.visible=false);return}const count=+$('#echo-frames').value;if(trailMeshes[0]?.geometry!==mesh.geometry){clearTrail();for(let i=0;i<count;i++){const ghost=new THREE.Mesh(mesh.geometry,material.clone());ghost.material.transparent=true;ghost.material.depthWrite=false;scene.add(ghost);trailMeshes.push(ghost)}}while(trailMeshes.length<count){const ghost=new THREE.Mesh(mesh.geometry,material.clone());ghost.material.transparent=true;ghost.material.depthWrite=false;scene.add(ghost);trailMeshes.push(ghost)}while(trailMeshes.length>count){const ghost=trailMeshes.pop();scene.remove(ghost);ghost.material.dispose()}if(now-trailLast>38){trailLast=now;trailHistory.unshift({position:mesh.position.clone(),rotation:mesh.rotation.clone(),scale:mesh.scale.clone()});trailHistory.length=count}trailMeshes.forEach((ghost,i)=>{const state=trailHistory[i+1];ghost.visible=!!state;if(!state)return;ghost.position.copy(state.position);ghost.rotation.copy(state.rotation);ghost.scale.copy(state.scale);ghost.material.color.copy(material.color);ghost.material.metalness=material.metalness;ghost.material.roughness=material.roughness;ghost.material.envMapIntensity=material.envMapIntensity;ghost.material.opacity=.42*(1-i/count);ghost.material.needsUpdate=true})}
function setBackgroundStyle(){const saturate=$('#saturation').value,bright=$('#brightness').value;viewport.style.filter=`saturate(${saturate}%) brightness(${bright}%)`;if(!bgTexture)scene.background=new THREE.Color($('#bg-color').value)}
function updateAfter(){if(!modelReady)return;afterCanvas.width=sourceCanvas.width;afterCanvas.height=sourceCanvas.height;afterCtx.drawImage(renderer.domElement,0,0,afterCanvas.width,afterCanvas.height)}
function frame(now){requestAnimationFrame(frame);const delta=Math.min(.05,(now-last)/1000);last=now;if(mesh&&isPlaying){const phase=Math.abs(Math.atan2(Math.sin(mesh.rotation.y),Math.cos(mesh.rotation.y))),t=Math.min(1,phase/.75),ease=t*t*(3-2*t),slowdown=+$('#slowdown').value/100;mesh.rotation.y+=delta*(+$('#speed').value/10)*(1-slowdown+slowdown*ease)}if(mesh&&neonLight.intensity>0){neonLight.position.copy(mesh.position);neonLight.position.z=52}updateTrail(now);controls.update();renderer.render(scene,camera);if(Math.round(now)%10===0)updateAfter()}requestAnimationFrame(frame);
function setEffect(){if(!material)return;const effect=$('.effects .chosen').dataset.effect,cfg={metal:{color:0xb7c6c2,roughness:.08,metalness:1,emissive:0x071116},hologram:{color:0x8dfff2,roughness:.05,metalness:.7,emissive:0x127b73},stone:{color:0x8d8b83,roughness:.94,metalness:0,emissive:0x000000},cracked:{color:0x382e29,roughness:.72,metalness:.08,emissive:0x000000},barbed:{color:0x90a7ad,roughness:.18,metalness:1,emissive:0x071116},liquid:{color:0xe0e9ff,roughness:.015,metalness:1,emissive:0x101a35},neon:{color:0x75f6ff,roughness:.2,metalness:.35,emissive:0x27d8ff}}[effect];material.color.setHex(cfg.color);material.roughness=cfg.roughness;material.metalness=cfg.metalness;material.emissive.setHex(cfg.emissive);material.emissiveIntensity=effect==='hologram'?1.65:effect==='neon'?3.8:.08;material.wireframe=effect==='barbed';material.transparent=effect==='hologram';material.opacity=effect==='hologram'?.84:1;material.clearcoat=0;material.clearcoatRoughness=0;material.envMapIntensity=1;neonLight.intensity=effect==='neon'?11:0;neonLight.color.set(0x4de7ff);scene.environment=studioEnvironment;if(selectedFinish==='chrome'){material.color.set(0xf5fbff);material.metalness=1;material.roughness=.045;material.clearcoat=1;material.clearcoatRoughness=.025;material.emissive.set(0x000000);material.emissiveIntensity=0;material.envMapIntensity=3.5;scene.environment=chromeEnvironment}material.needsUpdate=true}
function buildVectorModel(){const height=+$('#height').value,style=$('#volume-styles .chosen').dataset.volume,negative=$('#polarity .chosen').dataset.polarity==='negative',imageData=sourceCtx.getImageData(0,0,sourceCanvas.width,sourceCanvas.height),svg=ImageTracer.imagedataToSVG(imageData,{numberofcolors:2,colorquantcycles:1,pathomit:8,rightangleenhance:true,ltres:.6,qtres:.6,blurradius:0,scale:1}),paths=new SVGLoader().parse(svg).paths,geometries=[];for(const path of paths){if((path.color.r+path.color.g+path.color.b)/3>(negative?.45:.55))continue;for(const shape of SVGLoader.createShapes(path)){const g=new THREE.ExtrudeGeometry(shape,{depth:height,bevelEnabled:style==='balloon',bevelThickness:height*.12,bevelSize:1.5,bevelSegments:4,curveSegments:style==='balloon'?12:6});g.scale(118/sourceCanvas.width,-118/sourceCanvas.width,1);g.translate(-59,59,0);geometries.push(g)}}const merged=geometries.length?mergeGeometries(geometries):null;if(!merged){const keepVectorized=vectorized;vectorized=false;buildModel();vectorized=keepVectorized;return}geometry?.dispose();geometry=merged;if(mesh)scene.remove(mesh);material?.dispose();material=new THREE.MeshStandardMaterial({map:texture,color:0xb7c6c2,roughness:style==='balloon'?.18:.16,metalness:1,flatShading:style==='sharp'});mesh=new THREE.Mesh(geometry,material);scene.add(mesh);setEffect();setTransform()}
function buildModel(){if(!imageReady)return;const height=+$('#height').value,threshold=+$('#threshold').value,fill=+$('#fill').value/100,style=$('#volume-styles .chosen').dataset.volume,negative=$('#polarity .chosen').dataset.polarity==='negative',cols=80+Math.round(+$('#detail').value),ratio=sourceCanvas.width/sourceCanvas.height,rows=Math.max(18,Math.round(cols/ratio)),sample=document.createElement('canvas');sample.width=cols;sample.height=rows;const sc=sample.getContext('2d',{willReadFrequently:true});sc.imageSmoothingEnabled=!vectorized;sc.drawImage(sourceCanvas,0,0,cols,rows);const pix=sc.getImageData(0,0,cols,rows).data,mask=new Uint8Array(cols*rows),strength=new Float32Array(cols*rows),reachable=new Uint8Array(cols*rows),queue=[];for(let i=0;i<mask.length;i++){const k=i*4,l=.2126*pix[k]+.7152*pix[k+1]+.0722*pix[k+2],raw=negative?Math.max(0,Math.min(1,(l-(255-threshold))/threshold)):Math.max(0,Math.min(1,(threshold-l)/threshold)),a=vectorized?(raw>=.5?1:0):raw;if(a>=.1){mask[i]=1;strength[i]=a}}if(fill>0&&!negative){for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){if(x&&x<cols-1&&y&&y<rows-1)continue;const i=y*cols+x;if(!mask[i]&&!reachable[i]){reachable[i]=1;queue.push(i)}}for(let p=0;p<queue.length;p++){const i=queue[p],x=i%cols,y=(i-x)/cols;for(const n of [i-1,i+1,i-cols,i+cols]){if(n<0||n>=mask.length||Math.abs(n%cols-x)>1||Math.abs(((n-n%cols)/cols)-y)>1||mask[n]||reachable[n])continue;reachable[n]=1;queue.push(n)}}for(let i=0;i<mask.length;i++)if(!mask[i]&&!reachable[i]){mask[i]=1;strength[i]=fill}}const pos=[],idx=[],used=new Uint8Array(mask.length),sx=118/cols,sy=118/ratio/rows;let vi=0;const addBox=(x,y,w,h,s)=>{const x0=(x-cols/2)*sx,x1=x0+w*sx,y0=(rows/2-y)*sy,y1=y0-h*sy,z=height*(style==='balloon'?.7+.3*s:style==='sharp'?.9+.1*s:.78+.22*s);pos.push(x0,y0,0,x1,y0,0,x1,y1,0,x0,y1,0,x0,y0,z,x1,y0,z,x1,y1,z,x0,y1,z);for(const f of[[0,1,2,3],[4,7,6,5],[0,4,5,1],[1,5,6,2],[2,6,7,3],[3,7,4,0]])idx.push(vi+f[0],vi+f[1],vi+f[2],vi+f[0],vi+f[2],vi+f[3]);vi+=8};for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const i=y*cols+x;if(!mask[i]||used[i])continue;let w=1;while(x+w<cols&&mask[i+w]&&!used[i+w])w++;let h=1;outer:while(y+h<rows){for(let dx=0;dx<w;dx++)if(!mask[(y+h)*cols+x+dx]||used[(y+h)*cols+x+dx])break outer;h++}for(let dy=0;dy<h;dy++)for(let dx=0;dx<w;dx++)used[(y+dy)*cols+x+dx]=1;addBox(x,y,w,h,strength[i])}geometry?.dispose();geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geometry.setIndex(idx);geometry.computeVertexNormals();if(mesh)scene.remove(mesh);material?.dispose();material=new THREE.MeshStandardMaterial({map:texture,color:0xb7c6c2,roughness:style==='balloon'?.18:.22,metalness:.95,flatShading:style==='sharp'});mesh=new THREE.Mesh(geometry,material);scene.add(mesh);setEffect();setTransform()}
function loadDrawing(file){if(!file?.type.startsWith('image/')){$('#status').innerHTML='<i></i> Choisissez une image PNG, JPG ou WEBP';return}fileName=file.name;$('#file-name').textContent=file.name;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const scale=Math.min(1,1000/Math.max(img.width,img.height));sourceCanvas.width=Math.round(img.width*scale);sourceCanvas.height=Math.round(img.height*scale);sourceCtx.fillStyle='#fff';sourceCtx.fillRect(0,0,sourceCanvas.width,sourceCanvas.height);sourceCtx.drawImage(img,0,0,sourceCanvas.width,sourceCanvas.height);$('#import-preview').src=url;$('#live-source-preview').src=url;$('#live-source-preview').classList.add('visible');$('#dropzone').classList.add('has-preview');$('#import-title').textContent='Dessin importé';$('#import-help').textContent='Cliquez sur Modéliser en 3D pour lancer le rendu';imageReady=true;modelReady=false;isPlaying=false;$('#pause').textContent='▶ Lecture';$('#play-help').textContent='Modélisez le dessin pour lancer l’animation';$('#modelize').disabled=false;$('#record').disabled=true;$('#stl').disabled=true;$('#empty').classList.add('hidden');$('#status').className='ready';$('#status').innerHTML='<i></i> Dessin importé · aperçu original affiché'};img.onerror=()=>{URL.revokeObjectURL(url);$('#status').innerHTML='<i></i> Impossible de lire cette image'};img.src=url}
$('#file-input').addEventListener('change',e=>{loadDrawing(e.target.files[0]);e.target.value=''});const dz=$('#dropzone');['dragenter','dragover'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();e.stopPropagation();dz.classList.add('drag')}));['dragleave','dragend'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();dz.classList.remove('drag');loadDrawing(e.dataTransfer.files[0])});
$('#effects').addEventListener('click',e=>{if(!e.target.dataset.effect)return;selectedFinish=e.target.dataset.finish||'';$('.effects .chosen').classList.remove('chosen');e.target.classList.add('chosen');setEffect()});$('#motion-echo').addEventListener('click',()=>{trailEnabled=!trailEnabled;$('#motion-echo').textContent=trailEnabled?'Désactiver l’écho de mouvement':'Activer l’écho de mouvement';if(!trailEnabled)clearTrail()});$('#echo-frames').addEventListener('input',()=>{$('#echo-frames-out').textContent=$('#echo-frames').value});
$('#volume-styles').addEventListener('click',e=>{const button=e.target.closest('button[data-volume]');if(!button)return;$('#volume-styles .chosen').classList.remove('chosen');button.classList.add('chosen');if(modelReady)(vectorized?buildVectorModel():buildModel())});
$('#relief-profiles').addEventListener('click',e=>{const button=e.target.closest('button[data-relief]');if(!button)return;$('#relief-profiles .chosen').classList.remove('chosen');button.classList.add('chosen');const volume={geometric:'solid',smooth:'balloon',sharp:'sharp',spiky:'sharp'}[button.dataset.relief];$('#volume-styles .chosen').classList.remove('chosen');$(`#volume-styles [data-volume="${volume}"]`).classList.add('chosen');if(button.dataset.relief==='spiky'){$('#effects .chosen').classList.remove('chosen');$('#effects [data-effect="barbed"]').classList.add('chosen')}if(modelReady)(vectorized?buildVectorModel():buildModel())});
$('#polarity').addEventListener('click',e=>{const button=e.target.closest('button[data-polarity]');if(!button)return;$('#polarity .chosen').classList.remove('chosen');button.classList.add('chosen');if(modelReady)(vectorized?buildVectorModel():buildModel())});
$('#vectorize').addEventListener('click',()=>{vectorized=!vectorized;$('#vectorize').setAttribute('aria-pressed',String(vectorized));$('#vectorize').textContent=vectorized?'Vectorisation activée':'Vectoriser le dessin';if(modelReady)(vectorized?buildVectorModel():buildModel());$('#status').innerHTML=vectorized?'<i></i> Vectorisation active · contours nets':'<i></i> Vectorisation désactivée'});
$('#modelize').addEventListener('click',()=>{if(!imageReady)return;(vectorized?buildVectorModel():buildModel());modelReady=true;isPlaying=false;$('#pause').textContent='▶ Lecture';$('#live-source-preview').classList.remove('visible');$('#modelize').disabled=true;$('#demodelize').disabled=false;$('#record').disabled=false;$('#stl').disabled=false;$('#play-help').textContent='La rotation démarre avec Lecture';$('#status').className='ready';$('#status').innerHTML='<i></i> Modèle 3D prêt · appuyez sur Lecture'});
$('#demodelize').addEventListener('click',()=>{if(!imageReady)return;modelReady=false;isPlaying=false;if(mesh)scene.remove(mesh);$('#live-source-preview').classList.add('visible');$('#modelize').disabled=false;$('#demodelize').disabled=true;$('#record').disabled=true;$('#stl').disabled=true;$('#pause').textContent='▶ Lecture';$('#play-help').textContent='Modélisez le dessin pour lancer l’animation';$('#status').innerHTML='<i></i> Dessin original affiché'});
function applyTexture(url,temporary=false){new THREE.TextureLoader().load(url,t=>{texture?.dispose();texture=t;texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(3,3);if(material){material.map=texture;material.needsUpdate=true}if(temporary)URL.revokeObjectURL(url)})}
$('#texture-library').addEventListener('click',e=>{const button=e.target.closest('button[data-texture]');if(!button)return;document.querySelectorAll('#texture-library button').forEach(item=>item.classList.toggle('chosen',item===button));applyTexture(libraryTextures[button.dataset.texture]);$('#status').className='ready';$('#status').innerHTML='<i></i> Texture CC0 appliquée'});
$('#texture-input').addEventListener('change',e=>{const f=e.target.files[0];if(f)applyTexture(URL.createObjectURL(f),true)});
$('#bg-color').addEventListener('input',()=>{bgTexture=null;setBackgroundStyle()});$('#bg-image').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const u=URL.createObjectURL(f);new THREE.TextureLoader().load(u,t=>{bgTexture=t;scene.background=t;URL.revokeObjectURL(u)})});$('#bg-color').value='#000000';setBackgroundStyle();setLighting();
$('#pause').textContent='▶ Lecture';$('#pause').addEventListener('click',()=>{isPlaying=!isPlaying;$('#pause').textContent=isPlaying?'❚❚  Pause':'▶ Lecture'});$('#recenter').addEventListener('click',()=>{['position-x','position-y'].forEach(id=>{$('#'+id).value=0;$('#'+id+'-out').textContent='0'});setTransform()});document.querySelectorAll('.format button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.format-active').classList.remove('format-active');b.classList.add('format-active');viewport.classList.toggle('square',b.dataset.format==='square')}));
['profile','quality','duration'].forEach(id=>$('#'+id).addEventListener('change',refreshExportUi));refreshExportUi();
$('#add-accent-light').addEventListener('click',addAccentLight);$('#mirror-floor-toggle').addEventListener('click',()=>{mirrorFloor.visible=!mirrorFloor.visible;$('#mirror-floor-toggle').textContent=mirrorFloor.visible?'Désactiver le sol miroir':'Activer le sol miroir'});$('#randomize').addEventListener('click',randomizeScene);
$('#record').addEventListener('click',()=>{if(recording)return;recording=true;const o=exportOptions(),button=$('#record'),chunks=[],oldSize=renderer.getSize(new THREE.Vector2()),oldRatio=renderer.getPixelRatio(),oldAspect=camera.aspect;renderer.setPixelRatio(1);camera.aspect=o.w/o.h;camera.updateProjectionMatrix();renderer.setSize(o.w,o.h,false);const preferred='video/mp4;codecs=avc1.42E01E',mime=MediaRecorder.isTypeSupported(preferred)?preferred:'video/webm;codecs=vp9',extension=mime.startsWith('video/mp4')?'mp4':'webm',stream=renderer.domElement.captureStream(30),rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:o.bitrate});rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{renderer.setPixelRatio(oldRatio);renderer.setSize(oldSize.x,oldSize.y,false);camera.aspect=oldAspect;camera.updateProjectionMatrix();resize();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:mime}));a.download=(fileName.replace(/\.[^/.]+$/,'')||'reel')+'-3d.'+extension;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);recording=false;refreshExportUi();$('#status').innerHTML='<i></i> Vidéo prête au téléchargement'};rec.start();button.textContent='● Enregistrement…';$('#status').innerHTML='<i></i> Création de la vidéo '+o.seconds+' s';setTimeout(()=>rec.stop(),o.seconds*1000)});
$('#stl').addEventListener('click',()=>{if(!geometry)return;const p=geometry.getAttribute('position'),ind=geometry.getIndex(),v=i=>new THREE.Vector3(p.getX(i),p.getY(i),p.getZ(i));let s='solid calligraphy\n';for(let i=0;i<ind.count;i+=3){const a=v(ind.getX(i)),b=v(ind.getX(i+1)),c=v(ind.getX(i+2)),n=new THREE.Vector3().crossVectors(b.clone().sub(a),c.clone().sub(a)).normalize();s+=`facet normal ${n.x} ${n.y} ${n.z}\n outer loop\n  vertex ${a.x} ${a.y} ${a.z}\n  vertex ${b.x} ${b.y} ${b.z}\n  vertex ${c.x} ${c.y} ${c.z}\n endloop\nendfacet\n`}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s+'endsolid calligraphy\n'],{type:'model/stl'}));a.download='dessin-3d.stl';a.click()});
