import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { RoomEnvironment } from 'three/examples/jsm/environments/RoomEnvironment.js';
import { Reflector } from 'three/examples/jsm/objects/Reflector.js';
import { SVGLoader } from 'three/examples/jsm/loaders/SVGLoader.js';
import { mergeGeometries } from 'three/examples/jsm/utils/BufferGeometryUtils.js';
import ImageTracer from 'imagetracerjs';
import { GIFEncoder, quantize, applyPalette } from 'gifenc';
import { encodeAnimation } from 'wasm-webp';
import './style.css';
import './exports.css';
import './preview.css';
import './rebrand.css';
import './fidelity.css';
import './textures.css';
import './import-preview.css';
import './modelize.css';
import './volume.css';
import './vectorize.css';
import './compact-studio.css';
import './interaction-upgrades.css';

const $=s=>document.querySelector(s),sourceCanvas=$('#source-canvas'),sourceCtx=sourceCanvas.getContext('2d',{willReadFrequently:true}),afterCanvas=$('#after-canvas'),afterCtx=afterCanvas.getContext('2d');
let imageReady=false,modelReady=false,vectorized=true,geometry,mesh,material,texture,bgTexture,fileName='',isPlaying=false,last=performance.now(),recording=false,selectedFinish='chrome',trailEnabled=false,trailMeshes=[],trailHistory=[],trailLast=0,loopEnabled=true,mirrorGhost,lightEdit=false,transparentBg=false,motionPreset='spin',motionTime=0,lastFrameFit=0,startPose=null,bgFx='none';
const rawSourcePixels=sourceCtx.getImageData.bind(sourceCtx);sourceCtx.getImageData=(...args)=>{const pixels=rawSourcePixels(...args);if(!vectorized||!$('#threshold'))return pixels;const tolerance=+$('#threshold').value;for(let i=0;i<pixels.data.length;i+=4){const l=.2126*pixels.data[i]+.7152*pixels.data[i+1]+.0722*pixels.data[i+2],v=l<tolerance?0:255;pixels.data[i]=pixels.data[i+1]=pixels.data[i+2]=v}return pixels};
const viewport=$('#viewport'),stage=$('#stage'),scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(35,1,.1,1000),renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});
const pmrem=new THREE.PMREMGenerator(renderer),studioEnvironment=pmrem.fromScene(new RoomEnvironment(),.04).texture,chromeCanvas=document.createElement('canvas');chromeCanvas.width=1024;chromeCanvas.height=512;const chromeCtx=chromeCanvas.getContext('2d'),chromeGradient=chromeCtx.createLinearGradient(0,0,1024,0);chromeGradient.addColorStop(0,'#010103');chromeGradient.addColorStop(.12,'#080b0f');chromeGradient.addColorStop(.24,'#edf8ff');chromeGradient.addColorStop(.31,'#18232c');chromeGradient.addColorStop(.49,'#ffffff');chromeGradient.addColorStop(.59,'#101820');chromeGradient.addColorStop(.72,'#d6f4ff');chromeGradient.addColorStop(.82,'#06090d');chromeGradient.addColorStop(1,'#020204');chromeCtx.fillStyle=chromeGradient;chromeCtx.fillRect(0,0,1024,512);const chromeTexture=new THREE.CanvasTexture(chromeCanvas);chromeTexture.mapping=THREE.EquirectangularReflectionMapping;chromeTexture.colorSpace=THREE.SRGBColorSpace;const chromeEnvironment=pmrem.fromEquirectangular(chromeTexture).texture;scene.environment=chromeEnvironment;
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x101820,1);stage.append(renderer.domElement);camera.position.set(83,72,112);
const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=45;controls.maxDistance=250;controls.target.set(0,0,6);
const ambient=new THREE.HemisphereLight(0xd6f3ff,0x081311,1.1),key=new THREE.DirectionalLight(0xffefd0,3.4),rim=new THREE.DirectionalLight(0x68d7c3,1.4),neonLight=new THREE.PointLight(0x48dfff,0,180,2),mirrorFloor=new Reflector(new THREE.PlaneGeometry(600,600),{textureWidth:512,textureHeight:512,color:0x091017,clipBias:.003});scene.add(ambient,key,rim,neonLight);rim.position.set(-55,25,-35);mirrorFloor.rotateX(-Math.PI/2);mirrorFloor.position.y=-64;mirrorFloor.visible=false;scene.add(mirrorFloor);const accentLights=[],accentPalette=[0xff5f9f,0x6ae9ff,0xb68cff,0xffc66a];let accentIndex=0;
function resize(){const r=stage.getBoundingClientRect();camera.aspect=r.width/r.height;camera.updateProjectionMatrix();renderer.setSize(r.width,r.height)}new ResizeObserver(resize).observe(stage);resize();
function fitObjectInFrame(force=false){if(!mesh)return;const box=new THREE.Box3().setFromObject(mesh);if(box.isEmpty())return;const size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),verticalFov=THREE.MathUtils.degToRad(camera.fov),horizontalFov=2*Math.atan(Math.tan(verticalFov/2)*camera.aspect),distance=Math.max(size.y/(2*Math.tan(verticalFov/2)),size.x/(2*Math.tan(horizontalFov/2))+size.z*.55)*1.2;const direction=camera.position.clone().sub(controls.target);if(force||direction.length()<distance){camera.position.copy(center).add(direction.normalize().multiplyScalar(Math.max(distance,1)));controls.target.copy(center);camera.updateProjectionMatrix();controls.update()}}
viewport.insertAdjacentHTML('beforeend','<button id="light-gizmo" type="button" aria-label="Orienter la lumière" title="Glissez pour orienter la lumière"><span></span></button>');
$('.material-card').insertAdjacentHTML('beforeend','<div class="color-row"><label>Couleur métal<input id="material-color" type="color" value="#b7c6c2"/></label><label>Lueur<input id="emissive-color" type="color" value="#071116"/></label></div><label>Réflexion <output id="reflect-out">85 %</output></label><input id="reflect" type="range" min="0" max="100" value="85"/>');$('.light-card').insertAdjacentHTML('beforeend','<div class="color-row"><label>Clé<input id="light-color" type="color" value="#ffefd0"/></label><label>Contour<input id="rim-color" type="color" value="#68d7c3"/></label></div><label>Puissance <output id="light-power-out">100 %</output></label><input id="light-power" type="range" min="20" max="220" value="100"/><label>Exposition <output id="exposure-out">100 %</output></label><input id="exposure" type="range" min="40" max="180" value="100"/><button id="add-accent-light" class="secondary" type="button">＋ Ajouter une lumière d’accent</button><button id="light-live-toggle" class="secondary" type="button">◎ Déplacer la lumière dans l’aperçu</button>');$('.decor-card').insertAdjacentHTML('beforeend','<button id="mirror-floor-toggle" class="secondary" type="button">Activer le sol miroir</button><button id="transparent-bg" class="secondary" type="button">Fond transparent (GIF)</button>');
$('#effects').insertAdjacentHTML('beforeend','<button data-effect="metal" data-finish="translucent">Translucide</button><button data-effect="metal" data-finish="chrome">Métal chromé</button><button data-effect="neon">Néon lumineux</button>');
$('#height').max=100;$('#volume-styles').insertAdjacentHTML('afterend','<label>Relief de surface</label><div class="volume-styles" id="relief-profiles"><button class="chosen" data-relief="geometric">Géométrique</button><button data-relief="smooth">Lisse</button><button data-relief="sharp">Saillant</button><button data-relief="spiky">Épineux</button></div>');$('.motion-card').insertAdjacentHTML('beforeend','<label>Étirement en mouvement</label><button id="motion-echo" class="secondary" type="button">Activer l’écho de mouvement</button><label>Images fantômes <output id="echo-frames-out">8</output></label><input id="echo-frames" type="range" min="2" max="16" value="8"/><button id="loop-toggle" class="secondary" type="button">↻ Boucle : activée</button>');$('#demodelize').insertAdjacentHTML('afterend','<button id="randomize" class="secondary" type="button">✦ Paramètres aléatoires</button><button id="save-recipe" class="secondary" type="button">♢ Enregistrer une recette</button><select id="recipe-list"><option value="">Charger une recette…</option></select>');
$('#effects').insertAdjacentHTML('afterend','<p class="texture-library-title">Matières PBR</p><div class="effects" id="pbr-presets"><button data-pbr="plastic">Plastique</button><button data-pbr="mirror">Miroir</button><button data-pbr="gold">Or</button><button data-pbr="copper">Cuivre</button><button data-pbr="bronze">Bronze</button><button data-pbr="obsidian">Obsidienne</button><button data-pbr="marble">Marbre</button><button data-pbr="rubber">Caoutchouc</button><button data-pbr="ceramic">Céramique</button><button data-pbr="ice">Glace</button><button data-pbr="pearl">Nacre</button><button data-pbr="velvet">Velours</button></div>');$('.motion-card').insertAdjacentHTML('beforeend','<label>Mouvements prédéfinis</label><div class="effects" id="motion-presets"><button class="chosen" data-motion="spin">Rotation</button><button data-motion="orbit">Orbite</button><button data-motion="pirouette">Pirouette</button><button data-motion="bounce">Rebond</button><button data-motion="sway">Balancement</button><button data-motion="twist">Torsion</button></div>');
$('.transport').after($('.material-card'));viewport.insertAdjacentHTML('beforeend','<div id="bg-fx" aria-hidden="true"></div>');$('.decor-card').insertAdjacentHTML('beforeend','<p class="texture-library-title">Ambiance animée</p><div class="effects bg-effects" id="bg-effects"><button class="chosen" data-bgfx="none">Sans effet</button><button data-bgfx="flames">Flammes</button><button data-bgfx="smoke">Fumée</button><button data-bgfx="rain">Pluie</button></div>');$('.form-card').insertAdjacentHTML('beforeend','<button id="close-contours" class="secondary scene-toggle" type="button">Fermer les contours creux</button>');$('.motion-card').insertAdjacentHTML('beforeend','<button id="set-start-point" class="secondary scene-toggle" type="button">⌖ Définir ce point de départ</button>');
const units={height:' mm',threshold:'',detail:' %',fill:' %',scale:' %',light:'°',shadow:' %','light-power':' %',exposure:' %',reflect:' %',saturation:' %',brightness:' %',orientation:'°',speed:'×',slowdown:' %','position-x':'','position-y':''};
$('.motion-card').insertAdjacentHTML('beforeend','<div class="audio-card"><label>Audio <span id="audio-name">Aucun fichier</span></label><input id="audio-input" type="file" accept="audio/*"/><div><output id="audio-duration">00:00</output><button id="audio-loop" class="scene-toggle" type="button">Boucle désactivée</button></div></div>');
$('#stl').insertAdjacentHTML('afterend','<button id="gif" disabled>GIF animé</button><button id="sticker" disabled>Sticker WhatsApp</button>');
$('#randomize').insertAdjacentHTML('beforebegin','<button id="deform-drawing" class="secondary" type="button" disabled>≈ Déformer le dessin</button>');
const libraryTextures={wood:new URL('../assets/textures/fine-grained-wood-1k.jpg',import.meta.url).href,concrete:new URL('../assets/textures/rough-concrete-1k.jpg',import.meta.url).href,fabric:new URL('../assets/textures/fabric-pattern-05-1k.jpg',import.meta.url).href};
const profiles={instagram:{w:1080,h:1920,label:'Instagram Reel — 1080 × 1920'},square:{w:1080,h:1080,label:'Publication carrée — 1080 × 1080'},landscape:{w:1920,h:1080,label:'Paysage — 1920 × 1080'},'4k':{w:2160,h:3840,label:'Haute définition — 2160 × 3840'}};
function exportOptions(){const p=profiles[$('#profile').value],seconds=+$('#duration').value,quality=$('#quality').value,bitrate={standard:4500000,high:9000000,maximum:16000000}[quality];return{...p,seconds,bitrate}}
function refreshExportUi(){const o=exportOptions();$('#duration-label').textContent='00:'+String(o.seconds).padStart(2,'0');$('.timeline i').style.animationDuration=o.seconds+'s';$('#export-note').textContent=`${o.label}, 30 i/s, qualité ${$('#quality').selectedOptions[0].text.toLowerCase()}.`;$('#record').textContent=$('#profile').value==='instagram'?'● Créer la vidéo Instagram':'● Créer la vidéo'}
for(const id of Object.keys(units))$('#'+id).addEventListener('input',()=>{const val=+$('#'+id).value;$('#'+id+'-out').textContent=id==='speed'?(val/10).toFixed(1)+'×':val+units[id];if(id==='light'||id==='shadow')setLighting();else if(id==='scale'||id==='orientation'||id==='position-x'||id==='position-y')setTransform();else if(id==='speed'||id==='slowdown'){}else if(id==='saturation'||id==='brightness')setBackgroundStyle();else if(modelReady)(vectorized?buildVectorModel():buildModel())});
function setLighting(){const a=+$('#light').value*Math.PI/180,intensity=(1.1+(100-+$('#shadow').value)/35)*(+$('#light-power').value/100);key.position.set(Math.cos(a)*95,Math.sin(a)*95,60);key.intensity=intensity;key.color.set($('#light-color').value);rim.color.set($('#rim-color').value);ambient.intensity=.5+(100-+$('#shadow').value)/120;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=+$('#exposure').value/100;const gizmo=$('#light-gizmo');if(gizmo){gizmo.style.left=50+Math.cos(a)*38+'%';gizmo.style.top=50-Math.sin(a)*38+'%';gizmo.style.setProperty('--light-color',$('#light-color').value)}}
function addAccentLight(){const angle=(accentIndex*93+125)*Math.PI/180,light=new THREE.DirectionalLight(accentPalette[accentIndex%accentPalette.length],2.3);light.position.set(Math.cos(angle)*105,32+accentIndex%3*22,Math.sin(angle)*105);light.target.position.set(0,0,8);scene.add(light,light.target);accentLights.push(light);accentIndex++;$('#add-accent-light').textContent='＋ Lumières d’accent : '+accentLights.length}
function randomizeScene(){const set=(id,min,max)=>{const input=$('#'+id);input.value=Math.round(min+Math.random()*(max-min));input.dispatchEvent(new Event('input',{bubbles:true}))};set('height',6,38);set('threshold',70,200);set('detail',20,85);set('scale',75,120);set('light',0,360);set('shadow',20,80);set('light-power',60,180);set('exposure',70,135);set('orientation',0,360);set('speed',4,20);set('slowdown',30,92);set('position-x',-20,20);set('position-y',-14,14);$('#bg-color').value=['#03070f','#08000f','#07140f','#120607'][Math.floor(Math.random()*4)];setBackgroundStyle();const options=[...document.querySelectorAll('#effects button[data-effect]')],choice=options[Math.floor(Math.random()*options.length)];choice.click();$('#status').className='ready';$('#status').innerHTML='<i></i> Variante aléatoire générée'}
function deformDrawing(){if(!imageReady||modelReady)return;const temp=document.createElement('canvas'),ctx=temp.getContext('2d'),w=sourceCanvas.width,h=sourceCanvas.height;temp.width=w;temp.height=h;ctx.drawImage(sourceCanvas,0,0);sourceCtx.fillStyle='#fff';sourceCtx.fillRect(0,0,w,h);const amplitude=Math.max(7,w*.028),waves=2+Math.random()*3;for(let y=0;y<h;y++)sourceCtx.drawImage(temp,0,y,w,1,Math.sin(y/h*Math.PI*waves)*amplitude,y,w,1);const preview=sourceCanvas.toDataURL('image/png');$('#import-preview').src=preview;$('#live-source-preview').src=preview;$('#status').className='ready';$('#status').innerHTML='<i></i> Déformation appliquée · prête à modéliser'}
function recipes(){return JSON.parse(localStorage.getItem('reelforge-recipes')||'{}')}function refreshRecipes(){const select=$('#recipe-list'),saved=recipes();select.innerHTML='<option value="">Charger une recette…</option>'+Object.keys(saved).map(name=>'<option>'+name+'</option>').join('')}
async function exportGif(){if(!mesh)return;const gif=GIFEncoder(),savedRotation=mesh.rotation.y,profile=exportOptions(),scale=Math.min(1,640/Math.max(profile.w,profile.h)),width=Math.round(profile.w*scale/2)*2,height=Math.round(profile.h*scale/2)*2,format=transparentBg?'rgba4444':'rgb565',oldSize=renderer.getSize(new THREE.Vector2()),oldRatio=renderer.getPixelRatio(),oldAspect=camera.aspect;renderer.setPixelRatio(1);renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d');canvas.width=width;canvas.height=height;for(let i=0;i<30;i++){mesh.rotation.y=savedRotation+i*Math.PI*2/30;renderer.render(scene,camera);ctx.clearRect(0,0,width,height);ctx.drawImage(renderer.domElement,0,0,width,height);const data=ctx.getImageData(0,0,width,height).data,palette=quantize(data,128,{format,oneBitAlpha:transparentBg}),index=applyPalette(data,palette,format);gif.writeFrame(index,width,height,{palette,delay:55,repeat:0,transparent:transparentBg})}mesh.rotation.y=savedRotation;renderer.setPixelRatio(oldRatio);renderer.setSize(oldSize.x,oldSize.y,false);camera.aspect=oldAspect;camera.updateProjectionMatrix();gif.finish();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([gif.bytes()],{type:'image/gif'}));a.download=(fileName.replace(/\.[^/.]+$/,'')||'reel')+'-'+width+'x'+height+'.gif';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);$('#status').innerHTML='<i></i> GIF '+width+' × '+height+(transparentBg?' transparent':'')+' prêt au téléchargement'}
async function exportSticker(){if(!mesh)return;const button=$('#sticker'),size=512,frames=[],savedRotation=mesh.rotation.y,oldSize=renderer.getSize(new THREE.Vector2()),oldRatio=renderer.getPixelRatio(),oldAspect=camera.aspect,oldBackground=scene.background,oldFloor=mirrorFloor.visible;button.disabled=true;button.textContent='Création du sticker…';$('#status').innerHTML='<i></i> Création du sticker transparent…';try{scene.background=null;mirrorFloor.visible=false;renderer.setClearColor(0x000000,0);renderer.setPixelRatio(1);renderer.setSize(size,size,false);camera.aspect=1;camera.updateProjectionMatrix();const canvas=document.createElement('canvas'),ctx=canvas.getContext('2d',{willReadFrequently:true});canvas.width=size;canvas.height=size;for(let i=0;i<24;i++){mesh.rotation.y=savedRotation+i*Math.PI*2/24;renderer.render(scene,camera);ctx.clearRect(0,0,size,size);ctx.drawImage(renderer.domElement,0,0,size,size);frames.push({data:new Uint8Array(ctx.getImageData(0,0,size,size).data),duration:70,config:{lossless:0,quality:62}})}const bytes=await encodeAnimation(size,size,true,frames);if(!bytes)throw new Error('encodage impossible');const a=document.createElement('a'),blob=new Blob([bytes],{type:'image/webp'});a.href=URL.createObjectURL(blob);a.download=(fileName.replace(/\.[^/.]+$/,'')||'reel')+'-sticker-512.webp';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);const weight=Math.round(bytes.length/1024);$('#status').className='ready';$('#status').innerHTML='<i></i> Sticker animé 512 × 512 transparent prêt · '+weight+' Ko'+(weight>500?' — allégez le dessin pour WhatsApp':'')}catch(error){console.error(error);$('#status').innerHTML='<i></i> L’export sticker a échoué. Réessayez avec un dessin plus simple.'}finally{mesh.rotation.y=savedRotation;scene.background=oldBackground;mirrorFloor.visible=oldFloor;renderer.setClearColor(0x000000,transparentBg?0:1);renderer.setPixelRatio(oldRatio);renderer.setSize(oldSize.x,oldSize.y,false);camera.aspect=oldAspect;camera.updateProjectionMatrix();button.disabled=false;button.textContent='Sticker WhatsApp'}}
['light-power','exposure','light-color','rim-color'].forEach(id=>$('#'+id).addEventListener('input',setLighting));['material-color','emissive-color'].forEach(id=>$('#'+id).addEventListener('input',()=>{if(!material)return;material.color.set($('#material-color').value);material.emissive.set($('#emissive-color').value);material.needsUpdate=true}));$('#reflect').addEventListener('input',()=>{if(!material)return;material.metalness=+$('#reflect').value/100;material.roughness=1-(+$('#reflect').value/100)*.8;material.needsUpdate=true});
function setTransform(){if(!mesh)return;const s=+$('#scale').value/100;mesh.scale.setScalar(s);mesh.rotation.z=+$('#orientation').value*Math.PI/180;mesh.position.set(+$('#position-x').value,+$('#position-y').value,0);fitObjectInFrame(true)}
function applyPbr(name){if(!material)return;const p={plastic:[0xff2e7a,.28,.05],mirror:[0xf8ffff,.015,1],gold:[0xffbd34,.13,1],copper:[0xd77245,.18,1],bronze:[0x8a572c,.3,.9],obsidian:[0x090b12,.08,.65],marble:[0xece9e0,.55,.05],rubber:[0x171717,.88,0],ceramic:[0xf1f4ff,.16,.08],ice:[0x9deeff,.04,.12],pearl:[0xffd9f7,.19,.25],velvet:[0x3d124e,.76,0]}[name];material.color.setHex(p[0]);material.roughness=p[1];material.metalness=p[2];material.emissive.set(0x000000);material.transparent=name==='ice';material.opacity=name==='ice'?.62:1;material.envMapIntensity=name==='mirror'?3.5:1.2;material.needsUpdate=true}
function clearTrail(){trailMeshes.forEach(item=>{scene.remove(item);item.material.dispose()});trailMeshes=[];trailHistory=[]}
function updateTrail(now){if(!trailEnabled||!mesh||!material){trailMeshes.forEach(item=>item.visible=false);return}const count=+$('#echo-frames').value;if(trailMeshes[0]?.geometry!==mesh.geometry){clearTrail();for(let i=0;i<count;i++){const ghost=new THREE.Mesh(mesh.geometry,material.clone());ghost.material.transparent=true;ghost.material.depthWrite=false;scene.add(ghost);trailMeshes.push(ghost)}}while(trailMeshes.length<count){const ghost=new THREE.Mesh(mesh.geometry,material.clone());ghost.material.transparent=true;ghost.material.depthWrite=false;scene.add(ghost);trailMeshes.push(ghost)}while(trailMeshes.length>count){const ghost=trailMeshes.pop();scene.remove(ghost);ghost.material.dispose()}if(now-trailLast>38){trailLast=now;trailHistory.unshift({position:mesh.position.clone(),rotation:mesh.rotation.clone(),scale:mesh.scale.clone()});trailHistory.length=count}trailMeshes.forEach((ghost,i)=>{const state=trailHistory[i+1];ghost.visible=!!state;if(!state)return;ghost.position.copy(state.position);ghost.rotation.copy(state.rotation);ghost.scale.copy(state.scale);ghost.material.color.copy(material.color);ghost.material.metalness=material.metalness;ghost.material.roughness=material.roughness;ghost.material.envMapIntensity=material.envMapIntensity;ghost.material.opacity=.42*(1-i/count);ghost.material.needsUpdate=true})}
function updateMirror(){if(!mesh||!mirrorFloor.visible)return;if(!mirrorGhost||mirrorGhost.geometry!==mesh.geometry){if(mirrorGhost)scene.remove(mirrorGhost);mirrorGhost=new THREE.Mesh(mesh.geometry,material.clone());mirrorGhost.material.transparent=true;mirrorGhost.material.depthWrite=false;mirrorGhost.material.opacity=.34;scene.add(mirrorGhost)}mirrorGhost.visible=true;mirrorGhost.position.copy(mesh.position);mirrorGhost.position.y=2*mirrorFloor.position.y-mesh.position.y;mirrorGhost.rotation.copy(mesh.rotation);mirrorGhost.scale.copy(mesh.scale);mirrorGhost.scale.y*=-1;mirrorGhost.material.color.copy(material.color);mirrorGhost.material.metalness=material.metalness;mirrorGhost.material.roughness=.12;mirrorGhost.material.needsUpdate=true}
function setBackgroundStyle(){const saturate=$('#saturation').value,bright=$('#brightness').value;viewport.style.filter=`saturate(${saturate}%) brightness(${bright}%)`;if(!bgTexture)scene.background=new THREE.Color($('#bg-color').value)}
function updateAfter(){if(!modelReady)return;afterCanvas.width=sourceCanvas.width;afterCanvas.height=sourceCanvas.height;afterCtx.drawImage(renderer.domElement,0,0,afterCanvas.width,afterCanvas.height)}
function frame(now){requestAnimationFrame(frame);const delta=Math.min(.05,(now-last)/1000);last=now;if(mesh&&isPlaying){motionTime+=delta;const speed=+$('#speed').value/10,phase=Math.abs(Math.atan2(Math.sin(mesh.rotation.y),Math.cos(mesh.rotation.y))),t=Math.min(1,phase/.75),ease=t*t*(3-2*t),slowdown=+$('#slowdown').value/100;mesh.rotation.y+=delta*speed*(1-slowdown+slowdown*ease);if(motionPreset==='orbit'){mesh.position.x=Math.cos(motionTime*speed)*18;mesh.position.y=Math.sin(motionTime*speed)*12}else if(motionPreset==='pirouette')mesh.rotation.z+=delta*speed*2;else if(motionPreset==='bounce')mesh.position.y=Math.abs(Math.sin(motionTime*speed*2))*22;else if(motionPreset==='sway')mesh.rotation.z=Math.sin(motionTime*speed)*.45;else if(motionPreset==='twist'){mesh.rotation.x=Math.sin(motionTime*speed*2)*.45;mesh.rotation.z=Math.cos(motionTime*speed)*.25}if(!loopEnabled&&mesh.rotation.y>=Math.PI*2){mesh.rotation.y=0;isPlaying=false;$('#pause').textContent='▶ Lecture'}}if(mesh&&isPlaying&&now-lastFrameFit>180){lastFrameFit=now;fitObjectInFrame(false)}if(mesh&&neonLight.intensity>0){neonLight.position.copy(mesh.position);neonLight.position.z=52}updateMirror();updateTrail(now);controls.update();renderer.render(scene,camera);if(Math.round(now)%10===0)updateAfter()}requestAnimationFrame(frame);
function setEffect(){if(!material)return;const effect=$('.effects .chosen').dataset.effect,cfg={metal:{color:0xb7c6c2,roughness:.08,metalness:1,emissive:0x071116},hologram:{color:0x8dfff2,roughness:.05,metalness:.7,emissive:0x127b73},stone:{color:0x8d8b83,roughness:.94,metalness:0,emissive:0x000000},cracked:{color:0x382e29,roughness:.72,metalness:.08,emissive:0x000000},barbed:{color:0x90a7ad,roughness:.18,metalness:1,emissive:0x071116},liquid:{color:0xe0e9ff,roughness:.015,metalness:1,emissive:0x101a35},neon:{color:0x75f6ff,roughness:.2,metalness:.35,emissive:0x27d8ff}}[effect];material.color.setHex(cfg.color);material.roughness=cfg.roughness;material.metalness=cfg.metalness;material.emissive.setHex(cfg.emissive);material.emissiveIntensity=effect==='hologram'?1.65:effect==='neon'?3.8:.08;material.wireframe=effect==='barbed';material.transparent=effect==='hologram';material.opacity=effect==='hologram'?.84:1;material.clearcoat=0;material.clearcoatRoughness=0;material.envMapIntensity=1;neonLight.intensity=effect==='neon'?11:0;neonLight.color.set(0x4de7ff);scene.environment=studioEnvironment;if(selectedFinish==='chrome'){material.color.set(0xf5fbff);material.metalness=1;material.roughness=.045;material.clearcoat=1;material.clearcoatRoughness=.025;material.emissive.set(0x000000);material.emissiveIntensity=0;material.envMapIntensity=3.5;scene.environment=chromeEnvironment}material.needsUpdate=true}
function buildVectorModel(){const height=+$('#height').value,style=$('#volume-styles .chosen').dataset.volume,negative=$('#polarity .chosen').dataset.polarity==='negative',imageData=sourceCtx.getImageData(0,0,sourceCanvas.width,sourceCanvas.height),svg=ImageTracer.imagedataToSVG(imageData,{numberofcolors:2,colorquantcycles:1,pathomit:8,rightangleenhance:true,ltres:.6,qtres:.6,blurradius:0,scale:1}),paths=new SVGLoader().parse(svg).paths,geometries=[];for(const path of paths){if((path.color.r+path.color.g+path.color.b)/3>(negative?.45:.55))continue;for(const shape of SVGLoader.createShapes(path)){const g=new THREE.ExtrudeGeometry(shape,{depth:height,bevelEnabled:style==='balloon',bevelThickness:height*.12,bevelSize:1.5,bevelSegments:4,curveSegments:style==='balloon'?12:6});g.scale(118/sourceCanvas.width,-118/sourceCanvas.width,1);g.translate(-59,59,0);geometries.push(g)}}const merged=geometries.length?mergeGeometries(geometries):null;if(!merged){const keepVectorized=vectorized;vectorized=false;buildModel();vectorized=keepVectorized;return}geometry?.dispose();geometry=merged;if(mesh)scene.remove(mesh);material?.dispose();material=new THREE.MeshStandardMaterial({map:texture,color:0xb7c6c2,roughness:style==='balloon'?.18:.16,metalness:1,flatShading:style==='sharp'});mesh=new THREE.Mesh(geometry,material);scene.add(mesh);setEffect();setTransform()}
function buildModel(){if(!imageReady)return;const height=+$('#height').value,threshold=+$('#threshold').value,fill=+$('#fill').value/100,style=$('#volume-styles .chosen').dataset.volume,negative=$('#polarity .chosen').dataset.polarity==='negative',cols=80+Math.round(+$('#detail').value),ratio=sourceCanvas.width/sourceCanvas.height,rows=Math.max(18,Math.round(cols/ratio)),sample=document.createElement('canvas');sample.width=cols;sample.height=rows;const sc=sample.getContext('2d',{willReadFrequently:true});sc.imageSmoothingEnabled=!vectorized;sc.drawImage(sourceCanvas,0,0,cols,rows);const pix=sc.getImageData(0,0,cols,rows).data,mask=new Uint8Array(cols*rows),strength=new Float32Array(cols*rows),reachable=new Uint8Array(cols*rows),queue=[];for(let i=0;i<mask.length;i++){const k=i*4,l=.2126*pix[k]+.7152*pix[k+1]+.0722*pix[k+2],raw=negative?Math.max(0,Math.min(1,(l-(255-threshold))/threshold)):Math.max(0,Math.min(1,(threshold-l)/threshold)),a=vectorized?(raw>=.5?1:0):raw;if(a>=.1){mask[i]=1;strength[i]=a}}if(fill>0&&!negative){for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){if(x&&x<cols-1&&y&&y<rows-1)continue;const i=y*cols+x;if(!mask[i]&&!reachable[i]){reachable[i]=1;queue.push(i)}}for(let p=0;p<queue.length;p++){const i=queue[p],x=i%cols,y=(i-x)/cols;for(const n of [i-1,i+1,i-cols,i+cols]){if(n<0||n>=mask.length||Math.abs(n%cols-x)>1||Math.abs(((n-n%cols)/cols)-y)>1||mask[n]||reachable[n])continue;reachable[n]=1;queue.push(n)}}for(let i=0;i<mask.length;i++)if(!mask[i]&&!reachable[i]){mask[i]=1;strength[i]=fill}}const pos=[],idx=[],used=new Uint8Array(mask.length),sx=118/cols,sy=118/ratio/rows;let vi=0;const addBox=(x,y,w,h,s)=>{const x0=(x-cols/2)*sx,x1=x0+w*sx,y0=(rows/2-y)*sy,y1=y0-h*sy,z=height*(style==='balloon'?.7+.3*s:style==='sharp'?.9+.1*s:.78+.22*s);pos.push(x0,y0,0,x1,y0,0,x1,y1,0,x0,y1,0,x0,y0,z,x1,y0,z,x1,y1,z,x0,y1,z);for(const f of[[0,1,2,3],[4,7,6,5],[0,4,5,1],[1,5,6,2],[2,6,7,3],[3,7,4,0]])idx.push(vi+f[0],vi+f[1],vi+f[2],vi+f[0],vi+f[2],vi+f[3]);vi+=8};for(let y=0;y<rows;y++)for(let x=0;x<cols;x++){const i=y*cols+x;if(!mask[i]||used[i])continue;let w=1;while(x+w<cols&&mask[i+w]&&!used[i+w])w++;let h=1;outer:while(y+h<rows){for(let dx=0;dx<w;dx++)if(!mask[(y+h)*cols+x+dx]||used[(y+h)*cols+x+dx])break outer;h++}for(let dy=0;dy<h;dy++)for(let dx=0;dx<w;dx++)used[(y+dy)*cols+x+dx]=1;addBox(x,y,w,h,strength[i])}geometry?.dispose();geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geometry.setIndex(idx);geometry.computeVertexNormals();if(mesh)scene.remove(mesh);material?.dispose();material=new THREE.MeshStandardMaterial({map:texture,color:0xb7c6c2,roughness:style==='balloon'?.18:.22,metalness:.95,flatShading:style==='sharp'});mesh=new THREE.Mesh(geometry,material);scene.add(mesh);setEffect();setTransform()}
function loadDrawing(file){if(!file?.type.startsWith('image/')){$('#status').innerHTML='<i></i> Choisissez une image PNG, JPG ou WEBP';return}fileName=file.name;$('#file-name').textContent=file.name;const url=URL.createObjectURL(file),img=new Image();img.onload=()=>{const scale=Math.min(1,1000/Math.max(img.width,img.height));sourceCanvas.width=Math.round(img.width*scale);sourceCanvas.height=Math.round(img.height*scale);sourceCtx.fillStyle='#fff';sourceCtx.fillRect(0,0,sourceCanvas.width,sourceCanvas.height);sourceCtx.drawImage(img,0,0,sourceCanvas.width,sourceCanvas.height);$('#import-preview').src=url;$('#live-source-preview').src=url;$('#live-source-preview').classList.add('visible');$('#dropzone').classList.add('has-preview');$('#import-title').textContent='Dessin importé';$('#import-help').textContent='Cliquez sur Modéliser en 3D pour lancer le rendu';imageReady=true;modelReady=false;isPlaying=false;$('#pause').textContent='▶ Lecture';$('#play-help').textContent='Modélisez le dessin pour lancer l’animation';$('#modelize').disabled=false;$('#record').disabled=true;$('#stl').disabled=true;$('#empty').classList.add('hidden');$('#status').className='ready';$('#status').innerHTML='<i></i> Dessin importé · aperçu original affiché'};img.onerror=()=>{URL.revokeObjectURL(url);$('#status').innerHTML='<i></i> Impossible de lire cette image'};img.src=url}
$('#file-input').addEventListener('change',e=>{loadDrawing(e.target.files[0]);e.target.value=''});const dz=$('#dropzone');['dragenter','dragover'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();e.stopPropagation();dz.classList.add('drag')}));['dragleave','dragend'].forEach(t=>dz.addEventListener(t,e=>{e.preventDefault();dz.classList.remove('drag')}));dz.addEventListener('drop',e=>{e.preventDefault();e.stopPropagation();dz.classList.remove('drag');loadDrawing(e.dataTransfer.files[0])});
$('#file-input').addEventListener('change',()=>setTimeout(()=>{$('#deform-drawing').disabled=!imageReady},0));dz.addEventListener('drop',()=>setTimeout(()=>{$('#deform-drawing').disabled=!imageReady},0));$('#deform-drawing').addEventListener('click',deformDrawing);
$('#effects').addEventListener('click',e=>{if(!e.target.dataset.effect)return;selectedFinish=e.target.dataset.finish||'';$('.effects .chosen').classList.remove('chosen');e.target.classList.add('chosen');setEffect()});$('#motion-echo').addEventListener('click',()=>{trailEnabled=!trailEnabled;$('#motion-echo').textContent=trailEnabled?'Désactiver l’écho de mouvement':'Activer l’écho de mouvement';if(!trailEnabled)clearTrail()});$('#echo-frames').addEventListener('input',()=>{$('#echo-frames-out').textContent=$('#echo-frames').value});
$('#volume-styles').addEventListener('click',e=>{const button=e.target.closest('button[data-volume]');if(!button)return;$('#volume-styles .chosen').classList.remove('chosen');button.classList.add('chosen');if(modelReady)(vectorized?buildVectorModel():buildModel())});
$('#relief-profiles').addEventListener('click',e=>{const button=e.target.closest('button[data-relief]');if(!button)return;$('#relief-profiles .chosen').classList.remove('chosen');button.classList.add('chosen');const volume={geometric:'solid',smooth:'balloon',sharp:'sharp',spiky:'sharp'}[button.dataset.relief];$('#volume-styles .chosen').classList.remove('chosen');$(`#volume-styles [data-volume="${volume}"]`).classList.add('chosen');if(button.dataset.relief==='spiky'){$('#effects .chosen').classList.remove('chosen');$('#effects [data-effect="barbed"]').classList.add('chosen')}if(modelReady)(vectorized?buildVectorModel():buildModel())});
$('#polarity').addEventListener('click',e=>{const button=e.target.closest('button[data-polarity]');if(!button)return;$('#polarity .chosen').classList.remove('chosen');button.classList.add('chosen');if(modelReady)(vectorized?buildVectorModel():buildModel())});
$('#vectorize').addEventListener('click',()=>{vectorized=!vectorized;$('#vectorize').setAttribute('aria-pressed',String(vectorized));$('#vectorize').textContent=vectorized?'Vectorisation activée':'Vectoriser le dessin';if(modelReady)(vectorized?buildVectorModel():buildModel());$('#status').innerHTML=vectorized?'<i></i> Vectorisation active · contours nets':'<i></i> Vectorisation désactivée'});
$('#modelize').addEventListener('click',()=>{if(!imageReady)return;(vectorized?buildVectorModel():buildModel());modelReady=true;isPlaying=false;$('#pause').textContent='▶ Lecture';$('#live-source-preview').classList.remove('visible');$('#modelize').disabled=true;$('#demodelize').disabled=false;$('#record').disabled=false;$('#stl').disabled=false;$('#gif').disabled=false;$('#sticker').disabled=false;$('#play-help').textContent='La rotation démarre avec Lecture';$('#status').className='ready';$('#status').innerHTML='<i></i> Modèle 3D prêt · appuyez sur Lecture'});
$('#demodelize').addEventListener('click',()=>{if(!imageReady)return;modelReady=false;isPlaying=false;if(mesh)scene.remove(mesh);$('#live-source-preview').classList.add('visible');$('#modelize').disabled=false;$('#demodelize').disabled=true;$('#record').disabled=true;$('#stl').disabled=true;$('#gif').disabled=true;$('#sticker').disabled=true;$('#pause').textContent='▶ Lecture';$('#play-help').textContent='Modélisez le dessin pour lancer l’animation';$('#status').innerHTML='<i></i> Dessin original affiché'});
function applyTexture(url,temporary=false){new THREE.TextureLoader().load(url,t=>{texture?.dispose();texture=t;texture.colorSpace=THREE.SRGBColorSpace;texture.wrapS=texture.wrapT=THREE.RepeatWrapping;texture.repeat.set(3,3);if(material){material.map=texture;material.needsUpdate=true}if(temporary)URL.revokeObjectURL(url)})}
$('#texture-library')?.addEventListener('click',e=>{const button=e.target.closest('button[data-texture]');if(!button)return;document.querySelectorAll('#texture-library button').forEach(item=>item.classList.toggle('chosen',item===button));applyTexture(libraryTextures[button.dataset.texture]);$('#status').className='ready';$('#status').innerHTML='<i></i> Texture appliquée'});
$('#texture-input').addEventListener('change',e=>{const f=e.target.files[0];if(f)applyTexture(URL.createObjectURL(f),true)});
$('#bg-color').addEventListener('input',()=>{bgTexture=null;setBackgroundStyle()});$('#bg-image').addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const u=URL.createObjectURL(f);new THREE.TextureLoader().load(u,t=>{bgTexture=t;scene.background=t;URL.revokeObjectURL(u)})});$('#bg-color').value='#000000';setBackgroundStyle();setLighting();
$('#pause').textContent='▶ Lecture';$('#pause').addEventListener('click',()=>{isPlaying=!isPlaying;$('#pause').textContent=isPlaying?'❚❚  Pause':'▶ Lecture'});$('#recenter').addEventListener('click',()=>{['position-x','position-y'].forEach(id=>{$('#'+id).value=0;$('#'+id+'-out').textContent='0'});setTransform()});document.querySelectorAll('.format button').forEach(b=>b.addEventListener('click',()=>{document.querySelector('.format-active').classList.remove('format-active');b.classList.add('format-active');viewport.classList.toggle('square',b.dataset.format==='square')}));
['profile','quality','duration'].forEach(id=>$('#'+id).addEventListener('change',refreshExportUi));refreshExportUi();
$('#add-accent-light').addEventListener('click',addAccentLight);$('#mirror-floor-toggle').addEventListener('click',()=>{mirrorFloor.visible=!mirrorFloor.visible;$('#mirror-floor-toggle').textContent=mirrorFloor.visible?'Désactiver le sol miroir':'Activer le sol miroir'});$('#randomize').addEventListener('click',randomizeScene);
$('#loop-toggle').addEventListener('click',()=>{loopEnabled=!loopEnabled;$('#loop-toggle').textContent='↻ Boucle : '+(loopEnabled?'activée':'une rotation')});$('#gif').addEventListener('click',exportGif);$('#light-live-toggle').addEventListener('click',()=>{lightEdit=!lightEdit;controls.enabled=!lightEdit;$('#light-live-toggle').textContent=lightEdit?'Cliquez dans l’aperçu pour éclairer':'◎ Déplacer la lumière dans l’aperçu'});viewport.addEventListener('pointerdown',e=>{if(!lightEdit)return;const r=viewport.getBoundingClientRect(),x=(e.clientX-r.left)/r.width,y=(e.clientY-r.top)/r.height;$('#light').value=Math.round(x*360);$('#light-out').textContent=$('#light').value+'°';$('#light-power').value=Math.round(60+(1-y)*160);$('#light-power-out').textContent=$('#light-power').value+' %';setLighting()});$('#save-recipe').addEventListener('click',()=>{const name=prompt('Nom de la recette');if(!name)return;const ids=['height','threshold','detail','fill','scale','light','shadow','light-power','exposure','orientation','speed','slowdown','position-x','position-y','bg-color'];const recipe=Object.fromEntries(ids.map(id=>[id,$('#'+id).value]));recipe.effect=$('.effects .chosen').dataset.effect;const saved=recipes();saved[name]=recipe;localStorage.setItem('reelforge-recipes',JSON.stringify(saved));refreshRecipes();$('#recipe-list').value=name});$('#recipe-list').addEventListener('change',()=>{const recipe=recipes()[$('#recipe-list').value];if(!recipe)return;Object.entries(recipe).forEach(([id,value])=>{if(id==='effect'){const button=$('#effects [data-effect="'+value+'"]');if(button)button.click();return}const input=$('#'+id);if(input){input.value=value;input.dispatchEvent(new Event('input',{bubbles:true}))}});setLighting();setBackgroundStyle()});refreshRecipes();
$('#mirror-floor-toggle').addEventListener('click',()=>{if(mirrorGhost)mirrorGhost.visible=mirrorFloor.visible});
$('#sticker').addEventListener('click',exportSticker);
function pointLightAt(e){const r=viewport.getBoundingClientRect(),dx=(e.clientX-r.left)/r.width-.5,dy=.5-(e.clientY-r.top)/r.height,angle=(Math.atan2(dy,dx)*180/Math.PI+360)%360,power=Math.round(Math.min(220,Math.max(60,70+Math.hypot(dx,dy)*250)));$('#light').value=Math.round(angle);$('#light-out').textContent=Math.round(angle)+'°';$('#light-power').value=power;$('#light-power-out').textContent=power+' %';setLighting()}
$('#light-gizmo').addEventListener('pointerdown',e=>{e.preventDefault();e.stopPropagation();controls.enabled=false;$('#light-gizmo').setPointerCapture(e.pointerId);pointLightAt(e)});$('#light-gizmo').addEventListener('pointermove',e=>{if($('#light-gizmo').hasPointerCapture(e.pointerId))pointLightAt(e)});$('#light-gizmo').addEventListener('pointerup',e=>{if($('#light-gizmo').hasPointerCapture(e.pointerId))$('#light-gizmo').releasePointerCapture(e.pointerId);controls.enabled=true});
$('#transparent-bg').addEventListener('click',()=>{transparentBg=!transparentBg;scene.background=transparentBg?null:new THREE.Color($('#bg-color').value);renderer.setClearColor(0x000000,transparentBg?0:1);$('#transparent-bg').textContent=transparentBg?'Fond transparent : activé':'Fond transparent (GIF)'});
function captureStartPose(){if(mesh)startPose={position:mesh.position.clone(),rotation:mesh.rotation.clone(),scale:mesh.scale.clone()}}
function restoreStartPose(){if(!mesh||!startPose)return;mesh.position.copy(startPose.position);mesh.rotation.copy(startPose.rotation);mesh.scale.copy(startPose.scale);motionTime=0;fitObjectInFrame(true)}
$('#modelize').addEventListener('click',captureStartPose);$('#pause').addEventListener('click',()=>{viewport.classList.toggle('playing',isPlaying);if(isPlaying)restoreStartPose()});$('#set-start-point').addEventListener('click',()=>{captureStartPose();$('#set-start-point').classList.add('active');$('#set-start-point').textContent='✓ Point de départ enregistré'});
let audioTrack=null;$('#audio-input').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;if(audioTrack)audioTrack.pause();audioTrack=new Audio(URL.createObjectURL(file));$('#audio-name').textContent=file.name;audioTrack.addEventListener('loadedmetadata',()=>{$('#audio-duration').textContent='Durée '+Math.floor(audioTrack.duration/60).toString().padStart(2,'0')+':'+Math.floor(audioTrack.duration%60).toString().padStart(2,'0')})});$('#audio-loop').addEventListener('click',()=>{if(!audioTrack)return;audioTrack.loop=!audioTrack.loop;$('#audio-loop').classList.toggle('active',audioTrack.loop);$('#audio-loop').textContent=audioTrack.loop?'Boucle activée':'Boucle désactivée'});$('#pause').addEventListener('click',()=>{if(!audioTrack)return;if(isPlaying){audioTrack.currentTime=0;audioTrack.play().catch(()=>{})}else audioTrack.pause()});
$('#relief-profiles').addEventListener('click',e=>{const b=e.target.closest('button[data-relief]');if(!b)return;const boost={geometric:24,smooth:38,sharp:55,spiky:72}[b.dataset.relief];$('#height').value=boost;$('#height-out').textContent=boost+' mm';if(b.dataset.relief==='spiky'){$('#effects [data-effect="barbed"]').click();if(material)material.wireframe=false}if(modelReady)(vectorized?buildVectorModel():buildModel())});
$('#close-contours').addEventListener('click',()=>{const closing=$('#close-contours').classList.toggle('active');$('#fill').value=closing?100:0;$('#fill-out').textContent=$('#fill').value+' %';$('#close-contours').textContent=closing?'✓ Contours fermés':'Fermer les contours creux';if(modelReady)(vectorized?buildVectorModel():buildModel())});
$('#mirror-floor-toggle').addEventListener('click',()=>$('#mirror-floor-toggle').classList.toggle('active',mirrorFloor.visible));
$('#bg-effects').addEventListener('click',e=>{const b=e.target.closest('button[data-bgfx]');if(!b)return;bgFx=b.dataset.bgfx;$('#bg-effects').querySelectorAll('button').forEach(x=>x.classList.toggle('chosen',x===b));$('#bg-fx').className='fx-'+bgFx});
$('#effects').addEventListener('click',()=>{if(!material)return;if(selectedFinish==='oil'){material.color.set(0x5d6cff);material.roughness=.11;material.metalness=1;material.envMapIntensity=2.7;material.emissive.set(0x150720);material.emissiveIntensity=.2}if(selectedFinish==='bevel'){material.roughness=.09;material.metalness=1;material.envMapIntensity=3.1;material.flatShading=false;if(modelReady){$('#volume-styles [data-volume="balloon"]').click()}}material.needsUpdate=true});
$('#pbr-presets').addEventListener('click',e=>{const b=e.target.closest('button[data-pbr]');if(!b)return;$('#pbr-presets').querySelectorAll('button').forEach(x=>x.classList.toggle('chosen',x===b));applyPbr(b.dataset.pbr)});$('#motion-presets').addEventListener('click',e=>{const b=e.target.closest('button[data-motion]');if(!b)return;motionPreset=b.dataset.motion;motionTime=0;$('#motion-presets').querySelectorAll('button').forEach(x=>x.classList.toggle('chosen',x===b));setTransform()});
$('#record').addEventListener('click',()=>{if(recording)return;recording=true;const o=exportOptions(),button=$('#record'),chunks=[],oldSize=renderer.getSize(new THREE.Vector2()),oldRatio=renderer.getPixelRatio(),oldAspect=camera.aspect;renderer.setPixelRatio(1);camera.aspect=o.w/o.h;camera.updateProjectionMatrix();renderer.setSize(o.w,o.h,false);const preferred='video/mp4;codecs=avc1.42E01E',mime=MediaRecorder.isTypeSupported(preferred)?preferred:'video/webm;codecs=vp9',extension=mime.startsWith('video/mp4')?'mp4':'webm',stream=renderer.domElement.captureStream(30),rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:o.bitrate});rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);rec.onstop=()=>{renderer.setPixelRatio(oldRatio);renderer.setSize(oldSize.x,oldSize.y,false);camera.aspect=oldAspect;camera.updateProjectionMatrix();resize();const a=document.createElement('a');a.href=URL.createObjectURL(new Blob(chunks,{type:mime}));a.download=(fileName.replace(/\.[^/.]+$/,'')||'reel')+'-3d.'+extension;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);recording=false;refreshExportUi();$('#status').innerHTML='<i></i> Vidéo prête au téléchargement'};rec.start();button.textContent='● Enregistrement…';$('#status').innerHTML='<i></i> Création de la vidéo '+o.seconds+' s';setTimeout(()=>rec.stop(),o.seconds*1000)});
$('#stl').addEventListener('click',()=>{if(!geometry)return;const p=geometry.getAttribute('position'),ind=geometry.getIndex(),v=i=>new THREE.Vector3(p.getX(i),p.getY(i),p.getZ(i));let s='solid calligraphy\n';for(let i=0;i<ind.count;i+=3){const a=v(ind.getX(i)),b=v(ind.getX(i+1)),c=v(ind.getX(i+2)),n=new THREE.Vector3().crossVectors(b.clone().sub(a),c.clone().sub(a)).normalize();s+=`facet normal ${n.x} ${n.y} ${n.z}\n outer loop\n  vertex ${a.x} ${a.y} ${a.z}\n  vertex ${b.x} ${b.y} ${b.z}\n  vertex ${c.x} ${c.y} ${c.z}\n endloop\nendfacet\n`}const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([s+'endsolid calligraphy\n'],{type:'model/stl'}));a.download='dessin-3d.stl';a.click()});
