import './portfolio-library.css';

function initPortfolio() {
  if (new URLSearchParams(location.search).get('studio') !== 'portfolio') return;
  const workspace = document.querySelector('.workspace');
  if (!workspace) return;
  workspace.innerHTML = `<section class="book-library"><header><div><small>BIBLIOTHÈQUE DU BOOK</small><h2>Vos dossiers visuels</h2></div><button id="book-add-folder">＋ Nouveau dossier</button></header><div id="book-folders" class="book-folders"></div></section><aside class="book-gallery"><p id="book-folder-label">GALERIE</p><div class="book-title-row"><h2 id="book-folder-title">Sélectionnez un dossier</h2><button id="book-rename-folder" type="button" title="Renommer le dossier">✎</button></div><label class="book-import" id="book-drop-zone">Glissez vos dessins ici ou importez-les<input id="book-import-files" type="file" accept="image/png,image/jpeg,image/webp" multiple/></label><small id="book-status">Les visuels restent sur cet appareil.</small><div id="book-images" class="book-images"></div><button class="primary" id="book-present" disabled>Lancer la galerie</button></aside>`;
  const $ = selector => document.querySelector(selector), key = 'kanaforge-book-folders';
  const escape = value => String(value).replace(/[&<>'"]/g, character => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;' }[character]));
  const read = () => JSON.parse(localStorage.getItem(key) || 'null') || [{ id: 'fineline', name: 'Projet fineline', images: [] }, { id: 'lettering', name: 'Lettrage personnel', images: [] }, { id: 'botanical', name: 'Flash botanique', images: [] }];
  let folders = read(), activeId = folders[0]?.id;
  const save = () => localStorage.setItem(key, JSON.stringify(folders));
  const activeFolder = () => folders.find(folder => folder.id === activeId);
  const render = () => { const active = activeFolder(); $('#book-folders').innerHTML = `${folders.map(folder => `<button class="book-folder ${folder.id === activeId ? 'active' : ''}" data-folder="${folder.id}"><span>${folder.images[0] ? `<img src="${folder.images[0].image}" alt=""/>` : '✦'}</span><b>${escape(folder.name)}</b><small>${folder.images.length} visuel${folder.images.length > 1 ? 's' : ''}</small></button>`).join('')}<button class="book-folder add" id="book-add-tile"><span>＋</span><b>Nouveau dossier</b><small>Créer un dossier</small></button>`; $('#book-folder-label').textContent = active ? 'GALERIE DU DOSSIER' : 'GALERIE'; $('#book-folder-title').textContent = active?.name || 'Sélectionnez un dossier'; $('#book-images').innerHTML = active?.images.length ? active.images.map(image => `<figure><img src="${image.image}" alt="${escape(image.name)}"/><figcaption>${escape(image.name)} <button data-remove-image="${image.id}" aria-label="Retirer">×</button></figcaption></figure>`).join('') : '<p class="book-empty">Aucun dessin dans ce dossier.</p>'; $('#book-present').disabled = !active?.images.length; document.querySelectorAll('[data-folder]').forEach(button => button.onclick = () => { activeId = button.dataset.folder; render(); }); document.querySelectorAll('[data-remove-image]').forEach(button => button.onclick = () => { const folder = activeFolder(); folder.images = folder.images.filter(image => String(image.id) !== button.dataset.removeImage); save(); render(); }); $('#book-add-tile').onclick = addFolder; };
  const addFolder = () => { const name = prompt('Nom du nouveau dossier :'); if (!name?.trim()) return; const folder = { id: `folder-${Date.now()}`, name: name.trim(), images: [] }; folders.push(folder); activeId = folder.id; save(); render(); };
  const renameFolder = () => { const folder = activeFolder(); if (!folder) return; const name = prompt('Nouveau nom du dossier :', folder.name); if (!name?.trim() || name.trim() === folder.name) return; folder.name = name.trim(); save(); render(); $('#book-status').textContent = 'Dossier renommé.'; };
  const compactImage = file => new Promise((resolve, reject) => { const reader = new FileReader(); reader.onload = () => { const image = new Image(); image.onload = () => { const max = 1200, scale = Math.min(1, max / Math.max(image.width, image.height)), canvas = document.createElement('canvas'); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale)); canvas.getContext('2d').drawImage(image, 0, 0, canvas.width, canvas.height); resolve({ id: Date.now() + Math.random(), name: file.name || 'Visuel', image: canvas.toDataURL('image/jpeg', .86) }); }; image.onerror = reject; image.src = reader.result; }; reader.onerror = reject; reader.readAsDataURL(file); });
  const addFiles = async files => { const folder = activeFolder(); if (!folder) return; const usable = [...files].filter(file => file.type.startsWith('image/')).slice(0, 10); if (!usable.length) return; try { const images = await Promise.all(usable.map(compactImage)); folder.images.push(...images); folder.images = folder.images.slice(-24); save(); render(); $('#book-status').textContent = `${images.length} visuel(s) ajouté(s) dans ${folder.name}.`; } catch { $('#book-status').textContent = 'Un visuel n’a pas pu être importé.'; } };
  $('#book-add-folder').onclick = addFolder; $('#book-rename-folder').onclick = renameFolder; $('#book-import-files').onchange = event => addFiles(event.target.files); const drop = $('#book-drop-zone'); drop.addEventListener('dragover', event => { event.preventDefault(); drop.classList.add('dragging'); }); drop.addEventListener('dragleave', () => drop.classList.remove('dragging')); drop.addEventListener('drop', event => { event.preventDefault(); drop.classList.remove('dragging'); addFiles(event.dataTransfer.files); }); $('#book-present').onclick = () => { const folder = activeFolder(), viewer = document.createElement('div'); viewer.className = 'book-presenter'; viewer.innerHTML = `<button>×</button><h1>${escape(folder.name)}</h1><div>${folder.images.map(image => `<img src="${image.image}" alt="${escape(image.name)}"/>`).join('')}</div>`; document.body.append(viewer); viewer.querySelector('button').onclick = () => viewer.remove(); viewer.requestFullscreen?.().catch(() => {}); };
  render();
}

if (document.readyState === 'loading') addEventListener('DOMContentLoaded', initPortfolio, { once: true }); else queueMicrotask(initPortfolio);
